/**
 * English UI strings. Keys are the source of truth for StringKey type.
 */
export const stringsEn = {
  appTitle: 'STELLAR MINER',
  appSubtitle: 'Mine coins. Buy upgrades. Conquer the belt.',
  settings: 'Settings',
  settingsGroupVisual: 'Visual',
  settingsGroupGameplay: 'Gameplay',
  settingsGroupSaveData: 'Save & data',
  openSettings: 'Open settings',
  openAchievements: 'View achievements',
  close: 'Close',
  language: 'Language',
  languageEn: 'English',
  languageFr: 'Français',
  starfieldSpeed: 'Starfield speed',
  showOrbitLines: 'Show orbit lines',
  clickParticles: 'Click particles',
  compactNumbers: 'Compact numbers (1.2K)',
  spaceKeyRepeat: 'Allow Space key repeat (hold to mine)',
  layout: 'Layout',
  layoutTabs: 'Tabs',
  layoutOnePage: 'One page',
  pauseWhenBackground: 'Pause production when tab in background',
  exportSave: 'Export save',
  importSave: 'Import save',
  exportSaveTitle: 'Copy save to clipboard and download as file',
  importSaveTitle: 'Load a previously exported save (replaces current)',
  achievements: 'Achievements',
  resetProgress: 'Reset progress',
  resetConfirmTitle: 'Reset progress?',
  resetConfirmDesc: 'Coins, planets, upgrades, crew, achievements and all progress will be lost. This cannot be undone.',
  cancel: 'Cancel',
  resetAll: 'Reset all',
  prestigeConfirmTitle: 'Prestige?',
  prestigeConfirmDesc: "You'll reset to 0 coins and 1 planet. You keep your new Prestige level and +4% production per level forever.",
  prestige: 'Prestige',
  gotIt: 'Got it',
  coins: 'Coins',
  coinsTitle: 'Your current coins. Spend them on upgrades, crew, and planets.',
  production: 'Production',
  productionTitle: 'Empire × planets × prestige × events',
  productionClicksEstimate: '~{{n}} clicks/s',
  productionClicksWithRate: '~{{n}} clicks (+{{rate}}/s)',
  productionClicksRateOnly: 'clicks +{{rate}}/s',
  gameSections: 'Game sections',
  tabsMoreLabel: 'More sections',
  tabMine: 'Mine',
  tabDashboard: 'Dashboard',
  tabBase: 'Empire',
  tabResearch: 'Research',
  tabUpgrades: 'Upgrades',
  tabStats: 'Stats',
  dashboardTitle: 'Dashboard',
  dashboardOverview: 'Overview',
  dashboardQuickActions: 'Quick actions',
  dashboardQuestReady: 'Quest ready to claim',
  dashboardPrestigeReady: 'Prestige available',
  dashboardExpeditionInProgress: 'Expedition in progress',
  dashboardNextMilestone: 'Next milestone',
  goToMine: 'Go to Mine',
  goToEmpire: 'Go to Empire',
  goToUpgrades: 'Go to Upgrades',
  goToResearch: 'Go to Research',
  goToStats: 'Go to Stats',
  dashboardRecommended: 'Do this next',
  dashboardRunSummary: 'This run',
  dashboardTimeTo: '~{{min}} min to {{target}}',
  dashboardBuyOne: 'Buy {{name}}',
  dashboardKeepMining: 'Keep mining — tap Mine to earn faster',
  dashboardStartResearch: 'Try research: {{name}}',
  dashboardTimeToExpedition: '~{{min}} min to afford expedition',
  dashboardNeedCrewExpedition: 'Need {{n}} astronaut(s) for expedition — hire in Empire',
  dashboardAddSlot: 'Add a slot to place more upgrades',
  dashboardHireCrew: 'Hire astronauts to buy next upgrade',
  dashboardShortcuts: 'Shortcuts',
  dashboardQuestsShort: 'quests',
  dashboardEventsShort: 'events',
  dashboardToPrestige: 'To Prestige',
  dashboardSolarSystems: 'Systems',
  mineZoneTitle: 'Click or press Space to mine',
  keyboardShortcutsHint: 'Space to mine · 1–6 switch tabs',
  keyboardShortcutsSpaceKey: 'Space',
  keyboardShortcutsMine: 'to mine',
  keyboardShortcutsTabs: 'switch tabs',
  quest: 'Quest',
  questHint: 'Reach the target, then claim the reward. Claim within 5 min to build a streak and boost the next reward.',
  questRules: 'Quests give you a random target (e.g. "Earn 50K coins", "Have 10 astronauts"). Reach the target, then claim the reward.\n\n- Claim within 5 minutes of completing a quest to build a streak; your next reward is boosted.\n- If you wait too long, the streak resets and you start over.\n- Each new quest has a new random target and reward amount.',
  claim: 'Claim',
  prestigeHint: 'Reset your run to gain +4% production per level forever. Unlocks at the coin threshold shown below.',
  prestigeRules: 'Prestige resets your run (coins, planets, upgrades, crew, research) but you keep your Prestige level forever.\n\n- Each level gives +4% production on all future runs (stacking).\n- You need to reach the prestige coin threshold (shown in the section) to unlock the button.\n- Use it when progress feels slow — the permanent bonus will make the next run faster.',
  crew: 'Crew',
  astronautsLabel: 'Astronauts',
  crewHint: 'Hire astronauts (no job at first). Unlock Miner, Scientist, Pilot, Medic and Engineer via Research for bonuses. Some upgrades cost crew (assigned to equipment). Resets on Prestige.',
  crewRules: 'Astronauts give bonuses and are needed to buy some upgrades. Everything here resets on Prestige.\n\nFree crew (the numbers in the cards) give passive bonuses:\n- Miners: +2% production each.\n- Scientists: +2% research success chance each (capped).\n- Pilots: −8% expedition duration each (max 50% shorter).\n- Medics: −2% expedition death chance each.\n- Engineers: +1.2% production each.\n\nWhen you buy an upgrade that costs crew, that many astronauts are assigned to equipment — they no longer count as "free" but still count toward your total. Capacity comes from planets and housing (+2 per module). Veterans are expedition survivors and give +0.5% production each.',
  crewRecruitLabel: 'Recruit',
  noCrewYet: 'No crew yet',
  emptyCrewText: 'No crew yet. Hire astronauts below to boost production.',
  hireAstronaut: 'Hire astronaut',
  planets: 'Planets',
  emptyPlanetsText: 'No planets yet. Launch an expedition below to discover one.',
  emptyUpgradesText: 'Earn 30 coins to unlock upgrades.',
  planetsHint: 'More planets = +4% production each. Send an expedition (costs coins + crew; some may die) to discover one. Add slots or build housing (+2 crew capacity per module).',
  planetsRules: 'You start with one planet. Each planet has a limited number of slots for upgrades (and housing).\n\n- Each extra planet gives +4% production (stacking).\n- To get a new planet: send an expedition. It costs coins and crew; each astronaut has a chance to die. If at least one survives, you discover the planet. Pilots reduce expedition duration.\n- Add slots to a planet (costs coins) or build housing there: each housing module uses 1 slot and adds +2 to your total crew capacity.',
  housing: 'Housing',
  housingHint: 'Build housing on a planet to increase crew capacity (+2 astronauts per module). Each module uses 1 slot on that planet.',
  housingNoSlot: 'No free slot on any planet. Add a slot or use slots for upgrades.',
  housingBuilt: 'built',
  housingBuildTooltip: 'Build housing on {{planet}}: {{cost}} ⬡ · uses 1 slot · +{{capacity}} crew capacity.',
  needCoinsForHousing: 'Need {{cost}} ⬡ to build housing.',
  buildHousingBtn: 'Build housing ({{cost}} ⬡)',
  buyNewPlanet: 'Send expedition',
  upgrades: 'Upgrades',
  upgradesHint: 'Buy upgrades to boost production; each uses one slot on a planet. Some cost crew. Add slots or new planets to place more.',
  upgradesRules: 'Upgrades increase your production (coins per second). Each planet has a limited number of slots (6 on the first planet).\n\n- You can buy the same upgrade multiple times; each copy uses one slot on the planet you choose.\n- Some upgrades also cost crew: when you buy them, that many astronauts are assigned to equipment (see Crew section).\n- To place more upgrades: add slots to a planet or discover new planets.',
  research: 'Scientific Research',
  researchHint: 'Unlock nodes for +% production and +% click. Each attempt costs coins and has a success chance; scientists boost it. Resets on Prestige.',
  researchRules: 'The research tree unlocks permanent bonuses (+% production, +% click, and effects like "this upgrade no longer costs crew").\n\n- Unlock nodes by attempting them: each attempt costs coins and has a success chance. If it fails, the coins are lost and you can try again.\n- Scientists in your crew increase the success chance (capped).\n- All research progress resets on Prestige.',
  invalidSaveFile: 'Invalid save file.',
  errorOccurred: 'Something went wrong. Please try again.',
  offlineIndicator: 'You are offline. Progress may not be saved.',
  reducedMotion: 'Reduce motion',
  theme: 'Theme',
  themeLight: 'Light',
  themeDark: 'Dark',
  soundEnabled: 'Sound effects',
  debug: 'Debug',
  closeDebug: 'Close debug',

  starfieldSpeedSlow: 'Slow',
  starfieldSpeedNormal: 'Normal',
  starfieldSpeedFast: 'Fast',
  debugTriggerEvent: 'Trigger event',
  debugClearEvents: 'Clear events',
  debugF3Hint: 'F3 to toggle',
  firstPrestigeToast: 'First prestige!',
  firstUpgradeToast: 'First upgrade!',
  firstNewPlanetToast: 'First new planet!',
  firstAstronautToast: 'First astronaut!',
  expeditionDiscoveredWithDeaths: 'Discovered {{name}}! {{survivors}} astronaut(s) returned. {{deaths}} lost.',
  expeditionDiscoveredAllReturned: 'Discovered {{name}}! All {{survivors}} astronaut(s) returned.',
  expeditionFailed: 'Expedition failed. All {{n}} astronaut(s) lost. Planet not discovered.',
  chartLegendCoins: 'Coins ⬡',
  chartLegendProduction: 'Production /s',
  chartLegendTotalEver: 'Total ever ⬡',
  chartLegendCoinsGained: 'Gained ⬡',
  chartLegendCoinsPerClick: '⬡/click',
  chartLegendMinMaxPlaceholder: 'Min — · Max —',
  coinsGainedPerPeriod: 'Coins gained (per period)',
  coinsPerClickPerPeriod: 'Coins per click (per period)',
  chartAriaCoinsGained: 'Coins gained per period line chart. Hover to see values.',
  chartAriaCoinsPerClickPerPeriod: 'Average coins per click per period. Hover to see values.',
  chartDescCoins: 'Your current coin balance at each sample time. Goes up with production and clicks, down when you spend.',
  chartDescProduction: 'Empire production rate (coins per second) at each sample. Affected by upgrades, planets, prestige, events.',
  chartDescTotalEver: 'Cumulative coins earned since the start of the game. Never decreases.',
  chartDescCoinsGained: 'Coins earned in each time window (between two samples). Spikes when you earn a lot in a short time.',
  chartDescCoinsPerClickPerPeriod: 'In each time window: average coins earned per mine click. Rises with prestige, research, and events—shows how strong your clicks are over time.',
  chartDescClicksPerPeriod: 'Number of mine clicks in each time window. Shows how active you were in that period.',
  chartDescCoinsFromClicksPerPeriod: 'Coins earned from mine clicks only (no production) in each time window.',
  clicksPerPeriod: 'Clicks (per period)',
  coinsFromClicksPerPeriod: 'Coins from clicks (per period)',
  chartLegendClicks: 'Clicks',
  chartLegendCoinsFromClicks: 'From clicks ⬡',
  chartAriaClicks: 'Clicks per period line chart. Hover to see values.',
  chartAriaCoinsFromClicks: 'Coins from clicks per period line chart. Hover to see values.',
  achievementLockedTitle: '???',
  achievementSecret: '???',
  lastSavedJustNow: 'Saved',
  lastSavedAgo: 'Saved {{time}} ago',
  lastSavedSecs: '{{n}}s',
  lastSavedMins: '{{n}}m',
  researchFailedTryAgain: 'Research failed. Try again.',
  researching: 'Researching...',
  unknownResearch: 'Unknown research.',
  prerequisitesNotMet: 'Prerequisites not met or already unlocked.',
  notEnoughCoins: 'Not enough coins.',
  researchFailedCoinsSpent: 'Research failed. Coins spent. Try again.',
  researchNotEnoughCoins: 'Not enough coins anymore.',
  researchRequires: 'Requires: {{names}}',
  researchSlotFree: '{{n}} upgrade(s) no longer use a slot',
  researchCrewFree: '{{n}} upgrade(s) no longer require crew',
  researchUpgradeNoSlot: '{{name}}: no longer uses a slot',
  researchUpgradeNoCrew: '{{name}}: no longer requires crew',
  researchUpgradeLessSlot: '{{name}}: uses {{n}} less slot(s)',
  researchUpgradeLessCrew: '{{name}}: requires {{n}} less crew',
  researchUnlocksJob: 'Unlocks: {{role}} (Crew)',
  researchUnlockPath: 'Unlock path: {{path}}',
  researchUnlockPathSingle: 'Unlock path: {{name}}',
  researchEffectsLabel: 'Effects:',
  researchInfoTitle: 'Research details',
  researchAttemptTooltip: 'Attempt ({{pct}}% success). On failure, coins are lost.',
  researchAttemptDisabled: 'Complete prerequisites and have enough coins.',
  researchSuccessFormat: '{{name}} complete! {{mods}}.',
  attempt: 'Attempt',
  percentSuccess: '{{pct}}% success',
  researchScientistBonus: '(+{{pct}}% scientist)',
  claimRewardFormat: 'Claim {{reward}} ⬡',
  completeQuestToClaim: 'Complete the quest to claim the reward',
  questStreakKeep: 'Streak ×{{n}} · claim next within 5 min to keep it',
  streakExpired: 'Streak expired. Claim a quest to start a new streak.',
  achievementToast: 'Achievement: {{name}}',
  welcomeBack: 'Welcome back! +{{coins}} coins while you were away.',
  welcomeBackCapped: 'Welcome back! +{{coins}} coins while you were away (capped at 12h).',
  welcomeBackWithHours: 'You earned {{coins}} coins while away ({{hours}} h).',
  welcomeBackCappedWithHours: 'You earned {{coins}} coins while away ({{hours}} h, capped at 12h).',
  luckyToast: '★ LUCKY! +{{coins}} ⬡',
  questStreakToastFormat: 'Quest streak ×{{n}}! +{{pct}}% reward',
  milestoneToastFormat: 'Milestone: {{coins}} total coins earned!',
  dailyBonusToastFormat: 'Daily bonus: +{{n}} ⬡',
  criticalToastFormat: 'CRITICAL! +{{coins}} ⬡',
  prestigeMilestoneToastFormat: 'Prestige level {{level}}! +{{pct}}% production forever',
  crewStatFormat: 'Crew: {{n}} astronaut(s) available',
  crewStatDetail: '{{assigned}} on equipment · {{total}} total',
  crewStatByJob: '{{miners}} miners, {{scientists}} scientists, {{pilots}} pilots',
  crewStatRoleAstronauts: 'astronauts',
  crewStatRoleMiners: 'miners',
  crewStatRoleScientists: 'scientists',
  crewStatRolePilots: 'pilots',
  crewStatRoleMedics: 'medics',
  crewStatRoleEngineers: 'engineers',
  breakdownBase: 'Empire',
  breakdownPlanets: 'planets',
  breakdownPrestige: 'prestige',
  breakdownCrew: 'crew',
  breakdownResearch: 'research',
  breakdownEvent: 'event',
  nextMilestoneFormat: '{{remaining}} ⬡ to unlock {{title}}',
  nextMilestoneTime: '({{time}} at current rate)',
  toUnlock: 'to unlock',
  nextEventLabel: 'Next event',
  nextEventInFormat: 'Next event in {{time}}',
  eventBadgeTitle: '{{name}}: ×{{mult}} production',
  eventsHintTitle: 'Events you have seen',
  eventsHintWhat: 'Random events temporarily boost or reduce your production (e.g. ×2 for 30s). They unlock at 50,000 coins.',
  eventsHintHeading: 'Events you\'ve encountered',
  eventsHintEmpty: 'None yet. They will appear here once they occur.',
  eventsHintUnlock: 'Unlock events at 50,000 coins.',
  collapseSection: 'Collapse',
  expandSection: 'Expand',
  statisticsTitle: 'Statistics',
  statisticsHint: 'Charts and stats (economy, activity, run). Data is saved across sessions.',
  statisticsRules: 'Charts and stats for your mining empire. Data is saved across sessions.\n\n- Economy: coins over time, production rate, total coins ever.\n- Activity: clicks per period, coins earned from clicks — see how much you gain from clicking vs passive production.\n- Run stats: duration, coins earned, quests claimed, events, best combo. Resets on Prestige.',
  statisticsIntro: 'Track your mining empire: economy, progression, and activity. Chart data is saved across sessions.',
  chartsTitle: 'Charts',
  lastXMin: 'Last {{n}} min',
  lastXHours: 'Last {{n}} h',
  coinsOverTime: 'Coins over time',
  productionOverTime: 'Production over time',
  totalCoinsEverChart: 'Total coins ever',
  economyTitle: 'Economy',
  productionBreakdownTitle: 'Production breakdown',
  progressionTitle: 'Progression',
  activityTitle: 'Activity',
  runStatsTitle: 'This run',
  runDuration: 'Run duration',
  runCoinsEarned: 'Coins earned',
  runQuestsClaimed: 'Quests claimed',
  runEventsTriggered: 'Events triggered',
  runMaxCombo: 'Best combo (run)',
  runAvgCoinsPerSec: 'Avg coins/s (run)',
  questsEventsTitle: 'Quests & events',
  achievementsTitle: 'Achievements',
  currentCoins: 'Current coins',
  productionEffective: 'Production (effective)',
  totalCoinsEverLabel: 'Total coins ever',
  avgCoinsPerClick: 'Avg coins per click (session)',
  baseRate: 'Empire rate',
  planetBonus: 'Planet bonus',
  prestigeBonus: 'Prestige bonus',
  crewBonus: 'Crew bonus',
  eventMultiplier: 'Event multiplier',
  researchBonus: 'Research bonus',
  planetsCount: 'Planets',
  upgradesOwned: 'Upgrades owned',
  slotsUsedTotal: 'Slots used / total',
  prestigeLevel: 'Prestige level',
  prestigesToday: 'Prestiges today',
  researchNodesUnlocked: 'Research nodes',
  expeditionStatus: 'Expedition',
  expeditionStatInProgress: 'In progress ({{s}}s)',
  expeditionStatNone: '—',
  crewFree: 'Crew (free)',
  crewAssigned: 'Crew (assigned)',
  clicksLifetime: 'Clicks (lifetime)',
  clicksSession: 'Clicks (this session)',
  coinsFromClicksSession: 'Coins from clicks (session)',
  totalPlayTime: 'Total play time',
  sessionDuration: 'Session duration',
  playingSince: 'Playing since',
  peakProductionChart: 'Peak production (chart)',
  questStreak: 'Quest streak',
  activeEvents: 'Active events',
  nextEventIn: 'Next event in',
  unlockedLabel: 'Unlocked',
  chartMinMax: 'Min {{min}} · Max {{max}}',
  chartAriaCoins: 'Coins over time line chart. Hover to see values.',
  chartAriaProduction: 'Production over time line chart. Hover to see values.',
  chartAriaTotalEver: 'Total coins ever line chart. Hover to see values.',
  upgradeGroupEarly: 'Early',
  upgradeGroupMid: 'Mid',
  upgradeGroupLate: 'Late',
  buyLabel: 'Buy',
  buyLabelPlusOne: '+1',
  uninstallLabel: 'Uninstall',
  uninstallTitle: 'Uninstall one · refund {{cost}} ⬡',
  uninstallFrom: 'From',
  uninstallFromPlanet: 'Planet to uninstall from',
  maxLabel: 'Max',
  maxLabelCount: 'Max ({{n}})',
  recommended: 'Recommended',
  needAstronauts: 'Need {{n}} astronaut(s). Hire crew in the Crew section.',
  noFreeSlot: 'No free slot. Add a slot to a planet or buy a new planet!',
  needCoinsAndSlot: 'Need {{cost}} and a free slot.',
  buyUpgradeTitle: 'Buy {{name}} · {{cost}}',
  needCrewToBuy: 'Need more crew to buy this upgrade.',
  needCoinsForOne: 'Need {{cost}} to buy at least one.',
  noSlotsOrCoins: 'No free slots or not enough coins/crew to buy more.',
  toPlanet: 'To',
  assignToPlanet: 'Assign to planet',
  upgradeChoosePlanetInstallTitle: 'Choose planet to install on',
  upgradeChoosePlanetUninstallTitle: 'Choose planet to uninstall from',
  upgradeChoosePlanetSelect: 'Select',
  upgradeChoosePlanetExpand: 'Show details',
  upgradeChoosePlanetCollapse: 'Hide details',
  upgradeChoosePlanetInstalledOnPlanet: 'installed on this planet',
  tierLabel: 'Tier {{n}}',
  crewBadgeTitle: 'Cost in astronauts (spent when you buy)',
  crewCostShort: '{{n}} crew',
  upgradeUsesSlot: '1 slot',
  upgradeNoSlot: 'No slot',
  upgradePlanetAffinityTitle: 'Production by planet type',
  slots: 'slots',
  upgrading: 'Installing...',
  upgradingCount: 'Installing {{current}}/{{total}}',
  uninstallingCount: 'Uninstalling {{current}}/{{total}}',
  addSlotBtn: '+1 slot · {{cost}} ⬡',
  addSlotTooltip: 'Add one upgrade slot · {{cost}} ⬡',
  needCoinsForSlot: 'Need {{cost}} ⬡ to add a slot',
  sendExpeditionBtn: 'Send expedition ({{cost}} ⬡ + {{n}} crew)',
  sendExpeditionTooltip: 'Send {{n}} astronauts on expedition. Risk: some may die (28% each). If all die, planet not discovered. Cost: {{cost}} ⬡',
  needForExpedition: 'Need {{cost}} ⬡ and {{n}} astronauts to launch expedition',
  expeditionInProgress: 'Expedition in progress… {{seconds}}s remaining',
  expeditionCancel: 'Cancel expedition',
  expeditionModalTitle: 'Launch expedition',
  expeditionTierEasy: 'Easy',
  expeditionTierMedium: 'Medium',
  expeditionTierHard: 'Hard',
  expeditionTierEasyDesc: 'Lower risk, shorter trip.',
  expeditionTierMediumDesc: 'Standard risk and duration.',
  expeditionTierHardDesc: 'Higher risk, longer trip. Reward: +1 slot on the new planet.',
  expeditionTierRisk: '~{{pct}}% death chance each',
  expeditionTierDuration: '{{sec}}s',
  expeditionCrewSelect: 'Choose crew to send ({{required}} required)',
  expeditionLaunch: 'Launch expedition',
  expeditionSelectTier: 'Select a destination',
  expeditionSelectCrew: 'Assign {{required}} crew',
  planetCardTitle: '{{used}}/{{max}} slots',
  planetCardTitleProd: '{{used}}/{{max}} slots · +{{pct}}% prod from planets',
  planetInfoType: 'Type',
  planetInfoSlots: 'Slots',
  planetInfoProduction: 'Production',
  planetInfoHousing: 'Housing',
  planetInfoHousingLine: '{{n}} module(s) · +{{crew}} crew capacity',
  planetInfoEquipment: 'Equipment',
  planetInfoTitle: 'Planet info',
  hireAstronautCost: 'Hire astronaut · {{cost}} ⬡',
  hireAsRole: '{{role}} · {{cost}} ⬡',
  crewRoleAstronaut: 'Astronaut',
  crewRoleAstronautHint: 'No job bonus; counts for capacity and equipment. Unlock jobs via Research.',
  crewRoleMiner: 'Miner',
  crewRoleScientist: 'Scientist',
  crewRolePilot: 'Pilot',
  crewRoleMedic: 'Medic',
  crewRoleEngineer: 'Engineer',
  crewRoleMinerHint: '+2% production each',
  crewRoleScientistHint: '+2% research success chance each (capped)',
  crewRolePilotHint: '−8% expedition duration each (max 50% shorter)',
  crewRoleMedicHint: '−2% expedition death chance each',
  crewRoleEngineerHint: '+1.2% production each',
  crewVeterans: '{{n}} veteran(s) · +0.5% production each',
  crewBreakdown: '{{miners}} miners, {{scientists}} scientists, {{pilots}} pilots',
  noCrewYetMax: 'No crew yet (max {{max}})',
  crewSectionCount: '{{n}} astronaut(s)',
  crewLineAssigned: '{{assigned}} on equipment · 0 free (hire more for +% or discover planets to raise cap)',
  crewLineFree: '{{free}} free · +{{pct}}% production | {{assigned}} on equipment ({{total}}/{{max}})',
  crewLineAstronauts: '{{free}}/{{max}} astronaut(s) · +{{pct}}% production',
  crewSummary: '{{current}}/{{max}} astronauts · +{{pct}}% from crew',
  crewSummaryWithAssigned: '{{free}} free · {{assigned}} on equipment → {{total}}/{{max}} · +{{pct}}% from crew',
  crewSummaryNoBonus: '{{current}}/{{max}} astronauts',
  crewSummaryNoBonusWithAssigned: '{{free}} free · {{assigned}} on equipment → {{total}}/{{max}}',
  crewRoleEffectMiner: '+{{pct}}% production',
  crewRoleEffectScientist: '+{{pct}}% research success',
  crewRoleEffectPilot: '−{{pct}}% expedition time',
  crewRoleEffectMedic: '−{{pct}}% expedition death chance',
  crewRoleEffectEngineer: '+{{pct}}% production',
  crewInModules: '{{n}} astronaut(s) are on equipment — they were assigned when you bought upgrades that cost crew.',
  crewSegmentRole: '{{n}} {{role}}',
  crewSegmentEquipment: '{{n}} on equipment',
  crewSegmentFree: '{{n}} free slot(s)',
  crewOperatesHint: 'Hire crew to buy tier 3+ upgrades (each costs coins + astronauts).',
  crewOperatesNext: '{{free}} available. Next: {{name}} costs {{n}} crew.',
  crewOperatesUpgrades: '{{n}} upgrade(s) operated by crew.',
  crewOperatesAvailable: '{{free}} available.',
  freeAstronautsTitle: 'Free astronauts: +2% production each (miners). Others: scientists (research), pilots (expedition time). Max: {{max}}.',
  prestigeConfirmDescLevel: "You'll reset to 0 coins and 1 planet. You keep Prestige level {{level}} (+{{pct}}% production forever).",
  prestigeConfirmAfter: 'After Prestige: level {{level}} → +{{pct}}% production forever.',
  prestigeRewardsTitle: 'Prestige rewards',
  prestigeRewardsIntro: 'What you gain at each prestige level:',
  prestigeReward1: 'Prestige 1: +4% production forever. Unlocks all click bonuses: Lucky / Super Lucky / Critical clicks, Combo multiplier, and Research +% click (skill tree). Before prestige 1, each click gives only 1 coin.',
  prestigeRewardLevelFormat: 'Prestige {{level}}: +{{prod}}% production. Unlocks: +{{click}}% click forever.',
  prestigeRewardsWhatFor: 'What do I get?',
  eachPerSecond: '+{{n}}/s',
  totalPerSecond: 'Total: +{{n}}/s',
  needCoinsToBuy: 'Need {{cost}}{{crew}} to buy.',
  needCoinsAndCrew: 'Need {{cost}} + {{crew}} and a free slot.',
  maxBuyTooltip: 'Buy as many as you can afford with current slots',
  locked: 'Locked',
  debugCoinsRaw: 'Coins (raw)',
  debugProductionBase: 'Production (base)',
  debugProductionEffective: 'Production (effective)',
  debugEventMult: 'Event mult',
  debugPrestigeLevel: 'Prestige level',
  debugPlanets: 'Planets',
  debugUpgradesTotal: 'Upgrades total',
  debugNextEventIn: 'Next event in',
  debugActiveEvents: 'Active events',
  progressionWelcomeTitle: 'Welcome to Stellar Miner',
  progressionWelcomeBody: 'Click the asteroid (or press Space) to mine coins. Your goal: grow your mining operation by buying upgrades, hiring crew, and expanding to new planets. Start by mining until you can afford your first upgrade!',
  progressionUpgradesTitle: 'Upgrades',
  progressionUpgradesBody: 'Spend coins to buy equipment that produces coins automatically. Each upgrade adds production per second. You can buy the same upgrade multiple times—each goes on a planet slot. Start with a Mining Robot (45 ⬡).',
  progressionCrewTitle: 'Crew',
  progressionCrewBody: 'Hire astronauts to boost your production (+2% per astronaut). Better upgrades require crew to operate—you spend astronauts when you buy those upgrades. Hire your first astronaut when you can afford it (2,500 ⬡).',
  progressionQuestTitle: 'Quests',
  progressionQuestBody: 'Complete quests for bonus coins and rewards. Each quest has a target (e.g. mine X coins, buy upgrades). Claim within 5 minutes of completion for a streak bonus. Check the Quest section above.',
  progressionPlanetsTitle: 'Planets',
  progressionPlanetsBody: 'Send astronauts on expeditions to discover new planets (+4% production each). Some may die during the mission; if all die, the planet is not discovered. You can also add slots to existing planets.',
  progressionEventsTitle: 'Random events',
  progressionEventsBody: 'Space is full of surprises. Random events will now occasionally boost or reduce your production for a short time. Watch the event badges and plan around them!',
  progressionResearchTitle: 'Scientific Research',
  progressionResearchBody: 'Skill tree: attempt to unlock nodes for +% production and +% click. Each attempt can succeed or fail (coins lost on failure). Resets on Prestige.',
  progressionPrestigeTitle: 'Prestige',
  progressionPrestigeBody: 'When you reach 5,000,000 coins you can Prestige: reset coins and planets to gain +4% production per prestige level forever. Use it to progress faster on each new run.',
  versionLabel: 'Version',
  changelog: 'Changelog',
  whatsNew: "What's new",
  updateAvailable: 'New update',
  newUpdateAvailable: 'A new version is available. Open settings to see what\'s new.',
  infoTitle: "What's new",
  infoVersionLabel: 'Version',
  dashboardEmpty: 'No game session.',
  sectionRulesAria: 'Section rules',
  crewCapacityAria: 'Crew capacity',
  planetDetailTitle: 'Planet details',
  planetDetailSystem: 'System',
  planetDetailType: 'Type',
  planetDetailProduction: 'Production',
  planetDetailSlots: 'Slots',
  planetDetailHousing: 'Housing',
  planetDetailCrew: 'Crew assigned',
  planetDetailUpgrades: 'Installed upgrades',
  planetDetailNoUpgrades: 'No upgrades installed yet.',
  planetDetailMoons: 'Moons',
  planetDetailExtra: 'Features',
  planetDetailExtraNone: 'None',
  planetDetailExtraRings: 'Rings',
  planetDetailExtraBelt: 'Asteroid belt',
  planetDetailExtraRingsBelt: 'Rings & belt',
  planetDetailDragHint: 'Drag to rotate',
  planetDetailHousingModules: '{{n}} module(s) · +{{crew}} crew capacity',
  planetDetailNoHousing: 'No housing built.',
  planetDetailNoCrew: 'No crew assigned.',
  planetDetailCrewLine: '{{n}}/{{max}} assigned',
} as const;

export type StringKey = keyof typeof stringsEn;
