import type { StringKey } from "./en.js";

export const stringsFr: Record<StringKey, string> = {
  appTitle: 'STELLAR MINER',
  appSubtitle: 'Minez des pièces. Achetez des modules. Conquérez la ceinture.',
  settings: 'Paramètres',
  settingsGroupVisual: 'Affichage',
  settingsGroupGameplay: 'Jeu',
  settingsGroupSaveData: 'Sauvegarde et données',
  openSettings: 'Ouvrir les paramètres',
  openAchievements: 'Voir les succès',
  close: 'Fermer',
  language: 'Langue',
  languageEn: 'English',
  languageFr: 'Français',
  starfieldSpeed: 'Vitesse du champ d’étoiles',
  showOrbitLines: 'Afficher les orbites',
  clickParticles: 'Particules au clic',
  showTabLabels: 'Afficher les libellés des onglets',
  compactNumbers: 'Nombres compacts (1,2K)',
  spaceKeyRepeat: 'Répétition de la touche Espace (maintenir pour miner)',
  layout: 'Disposition',
  layoutTabs: 'Onglets',
  layoutOnePage: 'Une page',
  pauseWhenBackground: 'Pause de la production quand l’onglet est en arrière-plan',
  exportSave: 'Exporter la sauvegarde',
  importSave: 'Importer la sauvegarde',
  exportSaveTitle: 'Copier la sauvegarde et télécharger en fichier',
  importSaveTitle: 'Charger une sauvegarde (remplace la partie en cours).',
  achievements: 'Succès',
  resetProgress: 'Réinitialiser la progression',
  resetConfirmTitle: 'Réinitialiser la progression ?',
  resetConfirmDesc: 'Pièces, planètes, modules, équipage et toute la progression seront perdus. Irréversible.',
  cancel: 'Annuler',
  resetAll: 'Tout réinitialiser',
  prestigeConfirmTitle: 'Prestige ?',
  prestigeConfirmDesc: 'Vous repartez à 0 pièce et 1 planète. Vous gardez le niveau Prestige et +4 % de production par niveau.',
  prestige: 'Prestige',
  gotIt: 'Compris',
  coins: 'Pièces',
  coinsTitle: 'Vos pièces. Dépensez-les en modules, équipage et planètes.',
  production: 'Production',
  productionTitle: 'Empire × planètes × prestige × événements',
  productionClicksEstimate: '~{n} clics/s',
  productionClicksWithRate: '~{n} clics (+{rate}/s)',
  productionClicksRateOnly: 'clics +{rate}/s',
  gameSections: 'Sections du jeu',
  tabsMoreLabel: 'Plus de sections',
  tabMine: 'Mine',
  tabDashboard: 'Tableau de bord',
  tabBase: 'Empire',
  tabResearch: 'Recherche',
  tabUpgrades: 'Modules',
  tabStats: 'Stats',
  dashboardTitle: 'Tableau de bord',
  dashboardOverview: 'Vue d’ensemble',
  dashboardQuickActions: 'Actions rapides',
  dashboardQuestReady: 'Quête à réclamer',
  dashboardPrestigeReady: 'Prestige disponible',
  dashboardExpeditionInProgress: 'Expédition en cours',
  dashboardNextMilestone: 'Prochain jalon',
  goToMine: 'Aller à Mine',
  goToEmpire: 'Aller à Empire',
  goToUpgrades: 'Aller aux Modules',
  goToResearch: 'Aller à Recherche',
  goToStats: 'Aller aux Stats',
  dashboardRecommended: 'À faire',
  dashboardRunSummary: 'Cette run',
  dashboardTimeTo: '~{min} min pour {target}',
  dashboardBuyOne: 'Acheter {name}',
  dashboardKeepMining: 'Continue à miner — onglet Mine pour gagner plus vite',
  dashboardStartResearch: 'Tenter une recherche : {name}',
  dashboardTimeToExpedition: '~{min} min pour l’expédition',
  dashboardNeedCrewExpedition: 'Il faut {n} astronaute(s) pour l’expédition — engagez dans l’Empire',
  dashboardAddSlot: 'Ajouter un emplacement pour placer plus d’modules',
  dashboardHireCrew: 'Engager des astronautes pour la prochain module',
  dashboardShortcuts: 'Raccourcis',
  dashboardQuestsShort: 'quêtes',
  dashboardEventsShort: 'événements',
  dashboardToPrestige: 'Vers Prestige',
  dashboardSolarSystems: 'Systèmes',
  mineZoneTitle: 'Cliquez ou Espace pour miner',
  keyboardShortcutsHint: 'Espace pour miner · 1–6 changer d’onglet',
  keyboardShortcutsSpaceKey: 'Espace',
  keyboardShortcutsMine: 'pour miner',
  keyboardShortcutsTabs: 'changer d’onglet',
  quest: 'Quête',
  questHint: 'Atteignez l’objectif puis réclamez. Réclamez sous 5 min pour enchaîner une série et booster la prochaine récompense.',
  questRules: 'Les quêtes vous donnent un objectif aléatoire (ex. « Gagner 50K pièces », « Avoir 10 astronautes »). Atteignez l’objectif, puis réclamez la récompense.\n\n- Réclamez dans les 5 minutes après avoir terminé pour enchaîner une série ; la prochaine récompense est augmentée.\n- Si vous attendez trop, la série repart à zéro.\n- Chaque nouvelle quête a un nouvel objectif et montant aléatoires.',
  claim: 'Récupérer',
  prestigeHint: 'Réinitialisez la run pour gagner +4 % production par niveau pour toujours. Se débloque au seuil de pièces indiqué.',
  prestigeRules: 'Le Prestige réinitialise votre run (pièces, planètes, modules, équipage, recherche) mais vous gardez votre niveau de Prestige pour toujours.\n\n- Chaque niveau donne +4 % de production sur toutes les runs suivantes (cumulable).\n- Il faut atteindre le seuil de pièces indiqué dans la section pour débloquer le bouton.\n- Utilisez-le quand la progression semble lente — le bonus permanent rendra la prochaine run plus rapide.',
  crew: 'Équipage',
  astronautsLabel: 'Astronautes',
  crewHint: 'Recrutez des astronautes (sans métier au début). Débloquez Mineur, Scientifique, Pilote, Médecin et Ingénieur via la Recherche pour des bonus. Certaines modules coûtent du crew (assigné à l’équipement). Réinitialisé au Prestige.',
  crewRules: 'Les astronautes donnent des bonus et sont nécessaires pour acheter certains modules. Tout ici est réinitialisé au Prestige.\n\nL’équipage libre (les chiffres dans les cartes) donne des bonus passifs :\n- Mineurs : +2 % production chacun.\n- Scientifiques : +2 % de chance de succès en recherche chacun (plafonné).\n- Pilotes : −8 % de durée d’expédition chacun (max 50 % en moins).\n- Médecins : −2 % de risque de mort en expédition chacun.\n- Ingénieurs : +1,2 % production chacun.\n\nQuand vous achetez un module qui coûte du crew, ces astronautes sont assignés à l’équipement — ils ne comptent plus comme « libres » mais font toujours partie du total. La capacité vient des planètes et de l’habitat (+2 par module). Les vétérans sont des survivants d’expédition et donnent +0,5 % production chacun.',
  crewRecruitLabel: 'Recruter',
  noCrewYet: 'Pas encore d’équipage',
  emptyCrewText: 'Pas encore d’équipage. Engagez des astronautes ci-dessous pour booster la production.',
  hireAstronaut: 'Engager un astronaute',
  planets: 'Planètes',
  emptyPlanetsText: 'Pas encore de planètes. Lancez une expédition ci-dessous pour en découvrir une.',
  emptyUpgradesText: 'Gagnez 30 pièces pour débloquer les modules.',
  nextRecommended: 'Prochaine recommandation : {name}',
  planetsHint: 'Plus de planètes = +4 % production chacune. Envoyez une expédition (pièces + crew ; risque de mort) pour en découvrir. Ajoutez des emplacements ou construisez de l’habitat (+2 capacité crew par module).',
  planetsRules: 'Vous commencez avec une planète. Chaque planète a un nombre limité d’emplacements pour les modules (et l’habitat).\n\n- Chaque planète en plus donne +4 % de production (cumulable).\n- Pour avoir une nouvelle planète : envoyez une expédition. Elle coûte des pièces et du crew ; chaque astronaute a un risque de mourir. Si au moins un survit, vous découvrez la planète. Les pilotes réduisent la durée d’expédition.\n- Ajoutez des emplacements à une planète (coût en pièces) ou construisez de l’habitat : chaque module d’habitat utilise 1 emplacement et ajoute +2 à votre capacité d’équipage totale.',
  housing: 'Habitat',
  housingHint: "Construisez un habitat sur une planète pour augmenter la capacité d'équipage (+2 astronautes par module). Chaque module utilise 1 emplacement sur la planète.",
  housingNoSlot: 'Aucun emplacement libre sur les planètes. Ajoutez un emplacement ou utilisez-les pour des modules.',
  housingBuilt: 'construit(s)',
  housingBuildTooltip: "Construire un habitat sur {planet} : {cost} ⬡ · 1 emplacement · +{capacity} capacité d'équipage.",
  needCoinsForHousing: 'Il faut {cost} ⬡ pour construire un habitat.',
  buildHousingBtn: 'Construire un habitat ({cost} ⬡)',
  buyNewPlanet: 'Envoyer une expédition',
  upgrades: 'Modules',
  upgradesHint: 'Chaque carte affiche le tier, les types de planètes (chips), le nom, la production et le prix. Achetez des modules pour la production ; installez-les sur les planètes dont le type correspond pour un bonus. Chacun utilise un emplacement ; certains coûtent du crew. Ajoutez des emplacements ou des planètes pour en placer plus.',
  upgradesRules: 'Les modules augmentent votre production (pièces par seconde). Chaque planète a un nombre limité d’emplacements (6 sur la première).\n\n- Vous pouvez acheter le même module plusieurs fois ; chaque exemplaire utilise un emplacement sur la planète choisie.\n- Certains modules sont plus efficaces sur certains types de planètes : installez-les sur les planètes adaptées pour un bonus.\n- Certains modules coûtent aussi du crew : à l’achat, ces astronautes sont assignés à l’équipement (voir la section Équipage).\n- Pour placer plus d’modules : ajoutez des emplacements ou découvrez de nouvelles planètes.',
  research: 'Recherche scientifique',
  researchHint: 'Débloquez des nœuds pour + % production et + % clic. Chaque tentative coûte des pièces et a une chance de succès ; les scientifiques l’augmentent. Réinitialisé au Prestige.',
  researchTree3DHint: 'Glisser pour déplacer, molette pour zoomer, clic sur un nœud pour tenter.',
  researchTree3DZoomIn: 'Zoom avant',
  researchTree3DZoomOut: 'Zoom arrière',
  researchViewList: 'Liste',
  researchView3D: 'Arbre 3D',
  researchRules: 'L’arbre de recherche débloque des bonus permanents (+ % production, + % clic, et des effets comme « ce module ne coûte plus de crew »).\n\n- Débloquez les nœuds en les tentant : chaque tentative coûte des pièces et a une chance de succès. En cas d’échec, les pièces sont perdues et vous pouvez réessayer.\n- Les scientifiques dans votre équipage augmentent la chance de succès (plafonnée).\n- Toute la recherche est réinitialisée au Prestige.',
  invalidSaveFile: 'Fichier de sauvegarde invalide.',
  errorOccurred: 'Une erreur est survenue. Veuillez réessayer.',
  offlineIndicator: 'Vous êtes hors ligne. La progression peut ne pas être enregistrée.',
  reducedMotion: 'Réduire les animations',
  showStoryToasts: 'Toasts d’événements avec texte narratif',
  theme: 'Thème',
  themeLight: 'Clair',
  themeDark: 'Sombre',
  soundEnabled: 'Effets sonores',
  debug: 'Debug',
  closeDebug: 'Fermer le debug',

  starfieldSpeedSlow: 'Lent',
  starfieldSpeedNormal: 'Normal',
  starfieldSpeedFast: 'Rapide',
  debugTriggerEvent: 'Déclencher un événement',
  debugClearEvents: 'Effacer les événements',
  debugAddPlanet: '+1 planète',
  debugF3Hint: 'F3 pour afficher/masquer',
  firstPrestigeToast: 'Premier prestige !',
  firstUpgradeToast: 'Premier module !',
  firstNewPlanetToast: 'Première nouvelle planète !',
  firstAstronautToast: 'Premier astronaute !',
  expeditionDiscoveredWithDeaths: 'Découverte : {name} ! {survivors} astronaute(s) de retour. {deaths} perdu(s).',
  expeditionDiscoveredAllReturned: 'Découverte : {name} ! Tous les {survivors} astronaute(s) sont revenus.',
  expeditionFailed: 'Expédition échouée. Les {n} astronaute(s) ont péri. Planète non découverte.',
  chartLegendCoins: 'Pièces ⬡',
  chartLegendProduction: 'Production /s',
  chartLegendTotalEver: 'Total cumulé ⬡',
  chartLegendCoinsGained: 'Gagnées ⬡',
  chartLegendCoinsPerClick: '⬡/clic',
  chartLegendMinMaxPlaceholder: 'Min — · Max —',
  coinsGainedPerPeriod: 'Pièces gagnées (par période)',
  coinsPerClickPerPeriod: 'Pièces par clic (par période)',
  chartAriaCoinsGained: 'Graphique des pièces gagnées par période. Survolez pour voir les valeurs.',
  chartAriaCoinsPerClickPerPeriod: 'Moyenne de pièces par clic par période. Survolez pour voir les valeurs.',
  chartDescCoins: 'Votre solde de pièces à chaque prélèvement. Monte avec la production et les clics, baisse quand vous dépensez.',
  chartDescProduction: 'Taux de production de l\'empire (pièces par seconde) à chaque prélèvement. Dépend des modules, planètes, prestige, événements.',
  chartDescTotalEver: 'Pièces cumulées gagnées depuis le début. Ne baisse jamais.',
  chartDescCoinsGained: 'Pièces gagnées dans chaque fenêtre de temps (entre deux prélèvements). Monte en pic quand vous gagnez beaucoup en peu de temps.',
  chartDescCoinsPerClickPerPeriod: 'Dans chaque fenêtre : moyenne de pièces gagnées par clic mine. Monte avec le prestige, la recherche et les événements — montre la puissance de vos clics dans le temps.',
  chartDescClicksPerPeriod: 'Nombre de clics mine dans chaque fenêtre de temps. Montre à quel point vous étiez actif.',
  chartDescCoinsFromClicksPerPeriod: 'Pièces gagnées uniquement par les clics mine (sans la production) dans chaque fenêtre.',
  clicksPerPeriod: 'Clics (par période)',
  coinsFromClicksPerPeriod: 'Pièces des clics (par période)',
  chartLegendClicks: 'Clics',
  chartLegendCoinsFromClicks: 'Des clics ⬡',
  chartAriaClicks: 'Graphique des clics par période. Survolez pour voir les valeurs.',
  chartAriaCoinsFromClicks: 'Graphique des pièces des clics par période. Survolez pour voir les valeurs.',
  achievementLockedTitle: '???',
  achievementSecret: '???',
  lastSavedJustNow: 'Sauvegardé',
  lastSavedAgo: 'Sauvegardé il y a {time}',
  lastSavedSecs: '{n} s',
  lastSavedMins: '{n} min',
  researchFailedTryAgain: 'Échec de la recherche. Réessayez.',
  researching: 'Recherche en cours…',
  unknownResearch: 'Recherche inconnue.',
  prerequisitesNotMet: 'Prérequis non remplis ou déjà débloqué.',
  notEnoughCoins: 'Pas assez de pièces.',
  researchFailedCoinsSpent: 'Échec. Les pièces sont perdues. Réessayez.',
  researchNotEnoughCoins: 'Plus assez de pièces.',
  researchRequires: 'Requis : {names}',
  researchSlotFree: '{n} module(s) n’utilisent plus d’emplacement',
  researchCrewFree: '{n} module(s) ne nécessitent plus d’équipage',
  researchUpgradeNoSlot: '{name} : n’utilise plus d’emplacement',
  researchUpgradeNoCrew: '{name} : ne nécessite plus d’équipage',
  researchUpgradeLessSlot: '{name} : utilise {n} emplacement(s) de moins',
  researchUpgradeLessCrew: '{name} : nécessite {n} équipage en moins',
  researchUnlocksJob: 'Débloque : {role} (équipage)',
  researchUnlocksCrewRetrain: 'Débloque : reconversion du crew',
  researchUnlockPath: 'Parcours : {path}',
  researchUnlockPathSingle: 'Parcours : {name}',
  researchEffectsLabel: 'Effets :',
  researchInfoTitle: 'Détails de la recherche',
  researchAttemptTooltip: 'Tenter ({pct} % de succès). En cas d’échec, les pièces sont perdues.',
  researchAttemptDisabled: 'Remplissez les prérequis et ayez assez de pièces.',
  researchExpectedCost: 'Attendu ~{cost} ⬡',
  researchDurationSec: '~{sec}s',
  researchDataLabel: 'Données de recherche',
  researchDataRequirement: 'Requiert {n} données (expéditions)',
  researchPityNext: 'Prochaine tentative garantie (pity)',
  researchSuccessFormat: '{name} terminé ! {mods}.',
  attempt: 'Tenter',
  percentSuccess: '{pct} % de succès',
  researchScientistBonus: '(+{pct}% scientifique)',
  claimRewardFormat: 'Récupérer {reward} ⬡',
  completeQuestToClaim: 'Terminez la quête pour récupérer la récompense.',
  questStreakKeep: 'Série ×{n} · réclamez la prochaine sous 5 min pour la garder.',
  streakExpired: 'Série expirée. Réclamez une quête pour en commencer une nouvelle.',
  achievementToast: 'Succès : {name}',
  welcomeBack: 'Bon retour ! +{coins} pièces pendant votre absence.',
  welcomeBackCapped: 'Bon retour ! +{coins} pièces pendant votre absence (plafonné 12 h).',
  welcomeBackWithHours: 'Vous avez gagné {coins} pièces pendant votre absence ({hours} h).',
  welcomeBackCappedWithHours: 'Vous avez gagné {coins} pièces pendant votre absence ({hours} h, plafonné 12 h).',
  luckyToast: '★ CHANCE ! +{coins} ⬡',
  questStreakToastFormat: 'Série de quêtes ×{n} ! +{pct} % de récompense',
  milestoneToastFormat: 'Jalon : {coins} pièces gagnées au total !',
  dailyBonusToastFormat: 'Bonus quotidien : +{n} ⬡',
  criticalToastFormat: 'CRITIQUE ! +{coins} ⬡',
  prestigeMilestoneToastFormat: 'Niveau prestige {level} ! +{pct} % de production pour toujours',
  prestigeCompleteToast: 'Prestige ! +{pct} % production pour toujours.',
  prestigeCompleteToastWithChapter: 'Prestige {level} — {chapter} ! +{pct} % production pour toujours.',
  crewStatFormat: 'Équipage : {n} astronaute(s) disponible(s)',
  crewStatDetail: '{assigned} sur l’équipement · {total} au total',
  crewStatByJob: '{miners} mineurs, {scientists} scientifiques, {pilots} pilotes',
  crewStatRoleAstronauts: 'astronautes',
  crewStatRoleMiners: 'mineurs',
  crewStatRoleScientists: 'scientifiques',
  crewStatRolePilots: 'pilotes',
  crewStatRoleMedics: 'médecins',
  crewStatRoleEngineers: 'ingénieurs',
  breakdownBase: 'Empire',
  breakdownPlanets: 'planètes',
  breakdownPrestige: 'prestige',
  breakdownCrew: 'équipage',
  breakdownResearch: 'recherche',
  breakdownEvent: 'événement',
  nextMilestoneFormat: '{remaining} ⬡ pour débloquer {title}',
  nextMilestoneTime: '({time} au rythme actuel)',
  toUnlock: 'pour débloquer',
  nextEventLabel: 'Prochain événement',
  nextEventInFormat: 'Prochain événement dans {time}',
  eventBadgeTitle: '{name} : ×{mult} production',
  eventsHintTitle: 'Événements que vous avez vus',
  eventsHintWhat: 'Les événements aléatoires boostent ou réduisent votre production pendant un temps (ex. ×2 pendant 30 s). Ils se débloquent à 50 000 pièces.',
  eventsHintHeading: 'Événements déjà vécus',
  eventsHintEmpty: 'Aucun pour l’instant. Ils s’afficheront ici quand vous en aurez vus.',
  eventsHintUnlock: 'Débloquez les événements à 50 000 pièces.',
  collapseSection: 'Replier',
  expandSection: 'Déplier',
  statisticsTitle: 'Statistiques',
  statisticsHint: 'Graphiques et stats (économie, activité, run). Données conservées entre les sessions.',
  statisticsRules: 'Graphiques et stats de votre empire minier. Les données sont conservées entre les sessions.\n\n- Économie : pièces dans le temps, taux de production, total de pièces. Activité : clics par période, pièces gagnées par les clics — pour voir ce que rapportent les clics vs la production passive.\n- Stats de run : durée, pièces gagnées, quêtes réclamées, événements, meilleur combo. Réinitialisées au Prestige.',
  statisticsIntro: 'Suivez votre empire minier : économie, progression et activité. Les graphiques sont conservés entre les sessions.',
  chartsTitle: 'Graphiques',
  lastXMin: 'Dernières {n} min',
  lastXHours: 'Dernières {n} h',
  coinsOverTime: 'Pièces dans le temps',
  productionOverTime: 'Production dans le temps',
  totalCoinsEverChart: 'Total des pièces',
  economyTitle: 'Économie',
  productionBreakdownTitle: 'Détail de la production',
  progressionTitle: 'Progression',
  activityTitle: 'Activité',
  runStatsTitle: 'Cette run',
  runDuration: 'Durée de la run',
  runCoinsEarned: 'Pièces gagnées',
  runQuestsClaimed: 'Quêtes réclamées',
  runEventsTriggered: 'Événements déclenchés',
  runMaxCombo: 'Meilleur combo (run)',
  runAvgCoinsPerSec: 'Moy. pièces/s (run)',
  questsEventsTitle: 'Quêtes et événements',
  achievementsTitle: 'Succès',
  codexTitle: 'Archives',
  codexLockedPlaceholder: '???',
  codexCategoryAchievement: 'Succès',
  codexCategoryEvent: 'Événements',
  codexCategoryExpedition: 'Expéditions',
  codexCategoryPlanet: 'Planètes',
  codexCategoryPrestige: 'Prestige',
  codexCategoryQuest: 'Quêtes',
  codexCategoryResearch: 'Recherche',
  codexIntro: 'Logs et lore débloqués. De nouvelles entrées apparaissent en jouant.',
  currentCoins: 'Pièces actuelles',
  productionEffective: 'Production (effective)',
  totalCoinsEverLabel: 'Total des pièces',
  avgCoinsPerClick: 'Moy. pièces par clic (session)',
  baseRate: 'Taux empire',
  planetBonus: 'Bonus planètes',
  prestigeBonus: 'Bonus prestige',
  crewBonus: 'Bonus équipage',
  eventMultiplier: 'Multiplicateur événement',
  researchBonus: 'Bonus recherche',
  planetsCount: 'Planètes',
  upgradesOwned: 'Modules possédés',
  slotsUsedTotal: 'Emplacements utilisés / total',
  prestigeLevel: 'Niveau prestige',
  prestigesToday: 'Prestiges aujourd\'hui',
  researchNodesUnlocked: 'Nœuds recherche',
  expeditionStatus: 'Expédition',
  expeditionStatInProgress: 'En cours ({s} s)',
  expeditionStatNone: '—',
  crewFree: 'Équipage (libre)',
  crewAssigned: 'Équipage (assigné)',
  clicksLifetime: 'Clics (total)',
  clicksSession: 'Clics (cette session)',
  coinsFromClicksSession: 'Pièces des clics (session)',
  totalPlayTime: 'Temps de jeu total',
  sessionDuration: 'Durée de la session',
  playingSince: 'Joue depuis',
  peakProductionChart: 'Pic production (graphique)',
  questStreak: 'Série de quêtes',
  activeEvents: 'Événements actifs',
  nextEventIn: 'Prochain événement dans',
  unlockedLabel: 'Débloqués',
  chartMinMax: 'Min {min} · Max {max}',
  chartAriaCoins: 'Graphique des pièces dans le temps. Survolez pour voir les valeurs.',
  chartAriaProduction: 'Graphique de la production dans le temps. Survolez pour voir les valeurs.',
  chartAriaTotalEver: 'Graphique du total des pièces. Survolez pour voir les valeurs.',
  upgradeGroupEarly: 'Début',
  upgradeGroupMid: 'Milieu',
  upgradeGroupLate: 'Fin',
  buyLabel: 'Installer',
  buyLabelPlusOne: '+1',
  uninstallLabel: 'Désinstaller',
  uninstallTitle: 'Désinstaller un · remboursement {cost} ⬡',
  uninstallFrom: 'Depuis',
  uninstallFromPlanet: 'Planète depuis laquelle désinstaller',
  maxLabel: 'Max',
  maxLabelCount: 'Max ({n})',
  recommended: 'Recommandé',
  needAstronauts: 'Il faut {n} astronaute(s). Engagez-en dans la section Équipage.',
  noFreeSlot: 'Aucun emplacement libre. Ajoutez un emplacement ou achetez une planète !',
  needCoinsAndSlot: 'Il faut {cost} et un emplacement libre.',
  buyUpgradeTitle: 'Installer {name} · {cost}',
  needCrewToBuy: 'Il faut plus d’équipage pour installer ce module.',
  needCoinsForOne: 'Il faut {cost} pour en installer au moins un.',
  noSlotsOrCoins: 'Pas d’emplacement libre ou pas assez de pièces/équipage.',
  toPlanet: 'Vers',
  assignToPlanet: 'Assigner à la planète',
  upgradeChoosePlanetInstallTitle: 'Choisir la planète où installer',
  upgradeChoosePlanetUninstallTitle: 'Choisir la planète depuis laquelle désinstaller',
  upgradeChoosePlanetSelect: 'Choisir',
  upgradeChoosePlanetExpand: 'Afficher les détails',
  upgradeChoosePlanetCollapse: 'Masquer les détails',
  upgradeChoosePlanetInstalledOnPlanet: 'installés sur cette planète',
  upgradeChoosePlanetRecommendedHint: 'Type de planète idéal pour ce module — production supérieure.',
  tierLabel: 'Niveau {n}',
  crewBadgeTitle: 'Coût en astronautes (dépensés à l’installation)',
  crewCostShort: '{n} équipage',
  upgradeUsesSlot: '1 emplacement',
  upgradeNoSlot: 'Aucun emplacement',
  upgradePlanetAffinityTitle: 'Production selon le type de planète (installez sur les planètes adaptées pour un bonus)',
  moduleBestOn: 'Efficace sur : {types}',
  slots: 'emplacements',
  upgrading: 'Installation…',
  upgradingCount: 'Installation {current}/{total}',
  uninstallingCount: 'Désinstallation {current}/{total}',
  addSlotBtn: '+1 emplacement · {cost} ⬡',
  addSlotTooltip: 'Ajouter un emplacement d’module · {cost} ⬡',
  needCoinsForSlot: 'Il faut {cost} ⬡ pour ajouter un emplacement',
  sendExpeditionBtn: 'Envoyer une expédition ({cost} ⬡ + {n} équipage)',
  sendExpeditionTooltip: 'Envoyez {n} astronautes en expédition. Risque : certains peuvent mourir (28 % chacun). Si tous meurent, la planète n’est pas découverte. Coût : {cost} ⬡',
  needForExpedition: 'Il faut {cost} ⬡ et {n} astronautes pour lancer l’expédition',
  expeditionInProgress: 'Expédition en cours… {seconds} s restantes',
  expeditionCancel: 'Annuler l’expédition',
  expeditionModalTitle: 'Lancer une expédition',
  expeditionTierEasy: 'Facile',
  expeditionTierMedium: 'Moyen',
  expeditionTierHard: 'Difficile',
  expeditionTierEasyDesc: 'Risque réduit, voyage plus court.',
  expeditionTierMediumDesc: 'Risque et durée standards.',
  expeditionTierHardDesc: 'Risque plus élevé, voyage plus long. Récompense : +1 emplacement sur la nouvelle planète.',
  expeditionTierRisk: '~{pct} % de risque de mort chacun',
  expeditionTierDuration: '{sec} s',
  expeditionCrewSelect: 'Choisir l’équipage à envoyer ({required} requis)',
  expeditionLaunch: 'Lancer l’expédition',
  expeditionSelectTier: 'Choisir une destination',
  expeditionNewSolarSystem: 'Nouveau système',
  expeditionNewSolarSystemHint: 'Ce système est complet (4 planètes). La prochaine expédition part vers un nouveau système — coût plus élevé.',
  expeditionNewSolarSystemTooltipLine: 'Prochaine destination : un nouveau système solaire (coût plus élevé).',
  expeditionNextNewSystemLabel: 'Prochaine expédition : nouveau système (coût plus élevé).',
  expeditionSelectCrew: 'Assigner {required} équipage',
  planetCardTitle: '{used}/{max} emplacements',
  planetCardTitleProd: '{used}/{max} emplacements · +{pct} % prod. planètes',
  planetInfoType: 'Type',
  planetInfoSlots: 'Emplacements',
  planetInfoProduction: 'Production',
  planetInfoHousing: 'Habitat',
  planetInfoHousingLine: '{n} module(s) · +{crew} capacité équipage',
  planetInfoEquipment: 'Équipement',
  planetInfoTitle: 'Infos planète',
  hireAstronautCost: 'Engager un astronaute · {cost} ⬡',
  hireAsRole: '{role} · {cost} ⬡',
  crewRoleAstronaut: 'Astronaute',
  crewRoleAstronautHint: 'Aucun bonus métier ; compte pour la capacité et l’équipement. Débloquez les métiers via la Recherche.',
  crewRoleMiner: 'Mineur',
  crewRoleScientist: 'Scientifique',
  crewRolePilot: 'Pilote',
  crewRoleMedic: 'Médecin',
  crewRoleEngineer: 'Ingénieur',
  crewRoleMinerHint: '+2 % production chacun',
  crewRoleScientistHint: '+2 % chance de succès recherche chacun (plafonné)',
  crewRolePilotHint: '−8 % durée d’expédition chacun (max 50 % en moins)',
  crewRoleMedicHint: '−2 % risque de mort en expédition chacun',
  crewRoleEngineerHint: '+1,2 % production chacun',
  crewVeterans: '{n} vétéran(s) · +0,5 % production chacun',
  crewBreakdown: '{miners} mineurs, {scientists} scientifiques, {pilots} pilotes',
  noCrewYetMax: 'Pas encore d’équipage (max {max})',
  crewSectionCount: '{n} astronaute(s)',
  crewLineAssigned: '{assigned} sur l’équipement · 0 libre (engagez plus pour +% ou découvrez des planètes pour augmenter la capacité).',
  crewLineFree: '{free} libre · +{pct} % production | {assigned} sur l’équipement ({total}/{max})',
  crewLineAstronauts: '{free}/{max} astronaute(s) · +{pct} % production',
  crewSummary: '{current}/{max} astronautes · +{pct} % d’équipage',
  crewSummaryWithAssigned: '{free} libres · {assigned} sur l’équipement → {total}/{max} · +{pct} %',
  crewSummaryNoBonus: '{current}/{max} astronautes',
  crewSummaryNoBonusWithAssigned: '{free} libres · {assigned} sur l’équipement → {total}/{max}',
  crewRoleEffectMiner: '+{pct} % production',
  crewRoleEffectScientist: '+{pct} % succès recherche',
  crewRoleEffectPilot: '−{pct} % temps d’expédition',
  crewRoleEffectMedic: '−{pct} % risque de mort en expédition',
  crewRoleEffectEngineer: '+{pct} % production',
  crewInModules: '{n} astronaute(s) sont sur l’équipement — ils ont été assignés quand vous avez acheté des modules qui coûtaient du crew.',
  crewSegmentRole: '{n} {role}',
  crewSegmentEquipment: '{n} sur l’équipement',
  crewSegmentFree: '{n} emplacement(s) libre(s)',
  crewRetrainLabel: 'Reconvertir un crew',
  crewRetrainFrom: 'De',
  crewRetrainTo: 'Vers',
  crewRetrainBtn: 'Reconvertir · {cost} ⬡',
  crewOperatesHint: 'Engagez de l’équipage pour acheter les modules niveau 3+ (pièces + astronautes).',
  crewOperatesNext: '{free} disponible(s). Prochaine : {name} coûte {n} équipage.',
  crewOperatesUpgrades: '{n} module(s) opérée(s) par l’équipage.',
  crewOperatesAvailable: '{free} disponible(s).',
  freeAstronautsTitle: 'Astronautes libres : +2 % production (mineurs). Autres : scientifiques (recherche), pilotes (durée expédition). Max : {max}.',
  prestigeConfirmDescLevel: 'Vous repartez à 0 pièce et 1 planète. Vous gardez le niveau Prestige {level} (+{pct} % production pour toujours).',
  prestigeConfirmAfter: 'Après Prestige : niveau {level} → +{pct} % production pour toujours.',
  prestigeConfirmGainEstimate: 'Cette run : +{levelPct} % (niveau) +{planetPct} % (planètes) +{researchPct} % (recherche) = +{totalPct} % au total.',
  prestigeRewardsTitle: 'Récompenses de prestige',
  prestigeRewardsIntro: 'Ce que vous gagnez à chaque niveau de prestige :',
  prestigeReward1: 'Prestige 1 : +7 % production (niveau) plus +1 % par planète découverte et +0,5 % par recherche complétée (capitalisé au reset). Débloque les bonus de clic : Lucky / Super Lucky / Critical, multiplicateur Combo, et + % clic recherche (arbre). Avant le prestige 1, chaque clic ne donne qu’1 pièce.',
  prestigeRewardLevelFormat: 'Prestige {level} : +{prod} % production (niveau + planètes + recherche). Débloque : +{click} % clic pour toujours.',
  prestigeRewardsWhatFor: 'Qu’est-ce que je gagne ?',
  eachPerSecond: '+{n}/s',
  totalPerSecond: 'Total : +{n}/s',
  needCoinsToBuy: 'Il faut {cost}{crew} pour installer.',
  needCoinsAndCrew: 'Il faut {cost} + {crew} et un emplacement libre.',
  maxBuyTooltip: 'Installer autant que possible avec les emplacements actuels',
  locked: 'Verrouillé',
  debugCoinsRaw: 'Pièces (brut)',
  debugProductionBase: 'Production (base)',
  debugProductionEffective: 'Production (effective)',
  debugEventMult: 'Mult. événement',
  debugPrestigeLevel: 'Niveau prestige',
  debugPlanets: 'Planètes',
  debugUpgradesTotal: 'Total modules',
  debugNextEventIn: 'Prochain événement dans',
  debugActiveEvents: 'Événements actifs',
  progressionWelcomeTitle: 'Bienvenue dans Stellar Miner',
  progressionWelcomeBody: 'Cliquez sur l’astéroïde (ou Espace) pour miner des pièces.\n\nObjectif : développer votre opération en achetant des modules, en engageant de l’équipage et en découvrant des planètes. Minez jusqu’à pouvoir vous offrir votre première module !',
  progressionUpgradesTitle: 'Améliorations',
  progressionUpgradesBody: 'Dépensez des pièces pour acheter de l’équipement qui produit des pièces automatiquement. Chaque planète a un nombre limité d’emplacements (6 sur la première) : chaque robot ou foreuse en utilise un.\n\nCommencez par un Robot minier (45 ⬡), puis passez aux milliers, millions et au-delà.',
  progressionCrewTitle: 'Équipage',
  progressionCrewBody: 'Engagez des astronautes pour booster la production (+2 % par astronaute).\n\nLes meilleures modules nécessitent de l’équipage ; vous dépensez des astronautes à l’achat. Engagez votre premier astronaute quand vous pouvez (2 500 ⬡).',
  progressionQuestTitle: 'Quêtes',
  progressionQuestBody: 'Terminez des quêtes pour des pièces et récompenses bonus.\n\nChaque quête a un objectif (ex. miner X pièces, acheter des modules). Réclamez sous 5 minutes pour un bonus de série.',
  progressionPlanetsTitle: 'Planètes',
  progressionPlanetsBody: 'Envoyez des astronautes en expédition pour découvrir de nouvelles planètes (+4 % production chacune).\n\nCertains peuvent mourir ; si tous meurent, la planète n’est pas découverte. Vous pouvez aussi ajouter des emplacements aux planètes existantes.',
  progressionEventsTitle: 'Événements aléatoires',
  progressionEventsBody: "L'espace réserve des surprises.\n\nDes événements aléatoires vont désormais parfois augmenter ou réduire votre production pendant un court moment. Surveillez les badges d'événements !",
  progressionResearchTitle: 'Recherche scientifique',
  progressionResearchBody: 'Arbre de compétences : tentez de débloquer des nœuds pour + % production et + % clic.\n\nChaque tentative peut réussir ou échouer (pièces perdues en cas d’échec). Réinitialisé au Prestige.',
  progressionPrestigeTitle: 'Prestige',
  progressionPrestigeBody: 'À 5 000 000 pièces vous pouvez Prestige : réinitialiser pièces et planètes pour +4 % de production par niveau de prestige pour toujours.\n\nPour progresser plus vite à chaque run.',
  versionLabel: 'Version',
  changelog: 'Journal des modifications',
  whatsNew: 'Nouveautés',
  updateAvailable: 'Nouvelle mise à jour',
  newUpdateAvailable: 'Une nouvelle version est disponible. Ouvrez les paramètres pour voir les nouveautés.',
  infoTitle: 'Nouveautés',
  infoVersionLabel: 'Version',
  dashboardEmpty: 'Aucune partie en cours.',
  sectionRulesAria: 'Règles de la section',
  crewCapacityAria: 'Capacité d\'équipage',
  planetDetailTitle: 'Détails de la planète',
  planetDetailSystem: 'Système',
  planetDetailType: 'Type',
  planetDetailProduction: 'Production',
  planetDetailSlots: 'Emplacements',
  planetDetailHousing: 'Habitat',
  planetDetailCrew: 'Équipage assigné',
  planetDetailUpgrades: 'Modules installés',
  planetDetailNoUpgrades: 'Aucun module installé.',
  planetDetailMoons: 'Lunes',
  planetDetailExtra: 'Particularités',
  planetDetailExtraNone: 'Aucune',
  planetDetailExtraRings: 'Anneaux',
  planetDetailExtraBelt: 'Ceinture d\'astéroïdes',
  planetDetailExtraRingsBelt: 'Anneaux et ceinture',
  planetDetailDragHint: 'Glissez pour faire tourner',
  planetDetailHousingModules: '{n} module(s) · +{crew} capacité équipage',
  planetDetailNoHousing: 'Pas d\'habitat construit.',
  planetDetailNoCrew: 'Pas d\'équipage assigné.',
  planetDetailCrewLine: '{n}/{max} assigné(s)',
  planetDetailFirstContact: 'Premier contact',
  discoveryLogTitle: 'Journal des découvertes',
  discoveryLogEmpty: 'Aucune découverte. Envoyez une expédition pour trouver de nouvelles planètes.',
};
