/**
 * Centralized UI strings for i18n. Use t(key) in presentation layer.
 * Language from settings (en | fr).
 */
import { getSettings } from './gameState.js';

const stringsEn = {
  appTitle: 'STELLAR MINER',
  appSubtitle: 'Mine coins. Buy upgrades. Conquer the belt.',
  settings: 'Settings',
  openSettings: 'Open settings',
  close: 'Close',
  language: 'Language',
  languageEn: 'English',
  languageFr: 'Français',
  starfieldSpeed: 'Starfield speed',
  showOrbitLines: 'Show orbit lines',
  clickParticles: 'Click particles',
  compactNumbers: 'Compact numbers (1.2K)',
  spaceKeyRepeat: 'Allow Space key repeat (hold to mine)',
  layout: 'Layout',
  layoutTabs: 'Tabs',
  layoutOnePage: 'One page',
  pauseWhenBackground: 'Pause production when tab in background',
  exportSave: 'Export save',
  importSave: 'Import save',
  exportSaveTitle: 'Copy save to clipboard and download as file',
  importSaveTitle: 'Load a previously exported save (replaces current)',
  achievements: 'Achievements',
  resetProgress: 'Reset progress',
  resetConfirmTitle: 'Reset progress?',
  resetConfirmDesc: 'Coins, planets, upgrades, crew, achievements and all progress will be lost. This cannot be undone.',
  cancel: 'Cancel',
  resetAll: 'Reset all',
  prestigeConfirmTitle: 'Prestige?',
  prestigeConfirmDesc: "You'll reset to 0 coins and 1 planet. You keep your new Prestige level and +4% production per level forever.",
  prestige: 'Prestige',
  gotIt: 'Got it',
  coins: 'Coins',
  coinsTitle: 'Your current coins. Spend them on upgrades, crew, and planets.',
  production: 'Production',
  productionTitle: 'Empire × planets × prestige × events',
  gameSections: 'Game sections',
  tabsMoreLabel: 'More sections',
  tabMine: 'Mine',
  tabDashboard: 'Dashboard',
  tabBase: 'Empire',
  tabResearch: 'Research',
  tabUpgrades: 'Upgrades',
  tabStats: 'Stats',
  dashboardTitle: 'Dashboard',
  dashboardOverview: 'Overview',
  dashboardQuickActions: 'Quick actions',
  dashboardQuestReady: 'Quest ready to claim',
  dashboardPrestigeReady: 'Prestige available',
  dashboardExpeditionInProgress: 'Expedition in progress',
  dashboardNextMilestone: 'Next milestone',
  goToMine: 'Go to Mine',
  goToEmpire: 'Go to Empire',
  goToUpgrades: 'Go to Upgrades',
  goToResearch: 'Go to Research',
  goToStats: 'Go to Stats',
  dashboardRecommended: 'Do this next',
  dashboardRunSummary: 'This run',
  dashboardTimeTo: '~{{min}} min to {{target}}',
  dashboardBuyOne: 'Buy {{name}}',
  dashboardKeepMining: 'Keep mining — tap Mine to earn faster',
  dashboardStartResearch: 'Try research: {{name}}',
  dashboardTimeToExpedition: '~{{min}} min to afford expedition',
  dashboardShortcuts: 'Shortcuts',
  dashboardQuestsShort: 'quests',
  dashboardEventsShort: 'events',
  dashboardToPrestige: 'To Prestige',
  dashboardSolarSystems: 'Systems',
  mineZoneTitle: 'Click or press Space to mine',
  keyboardShortcutsHint: 'Space to mine · 1–6 switch tabs',
  keyboardShortcutsSpaceKey: 'Space',
  keyboardShortcutsMine: 'to mine',
  keyboardShortcutsTabs: 'switch tabs',
  quest: 'Quest',
  questHint: 'Reach the target, then claim the reward. Claim within 5 min to build a streak and boost the next reward.',
  questRules: 'Quests give you a random target (e.g. "Earn 50K coins", "Have 10 astronauts"). Reach the target, then claim the reward.\n\n- Claim within 5 minutes of completing a quest to build a streak; your next reward is boosted.\n- If you wait too long, the streak resets and you start over.\n- Each new quest has a new random target and reward amount.',
  claim: 'Claim',
  prestigeHint: 'Reset your run to gain +4% production per level forever. Unlocks at the coin threshold shown below.',
  prestigeRules: 'Prestige resets your run (coins, planets, upgrades, crew, research) but you keep your Prestige level forever.\n\n- Each level gives +4% production on all future runs (stacking).\n- You need to reach the prestige coin threshold (shown in the section) to unlock the button.\n- Use it when progress feels slow — the permanent bonus will make the next run faster.',
  crew: 'Crew',
  crewHint: 'Hire by role. Miners +2% production; scientists +2% research success; pilots guarantee one expedition survivor. Some upgrades cost crew (they get assigned to equipment). Resets on Prestige.',
  crewRules: 'Astronauts give bonuses and are needed to buy some upgrades. Everything here resets on Prestige.\n\nFree crew (the numbers in the cards) give passive bonuses:\n- Miners: +2% production each.\n- Scientists: +2% research success chance each (capped).\n- Pilots: guarantee at least one survivor on expeditions.\n\nWhen you buy an upgrade that costs crew, that many astronauts are assigned to equipment — they no longer count as "free" but still count toward your total. Capacity comes from planets and housing (+2 per module). Veterans are expedition survivors and give +0.5% production each.',
  crewRecruitLabel: 'Recruit',
  noCrewYet: 'No crew yet',
  hireAstronaut: 'Hire astronaut',
  planets: 'Planets',
  planetsHint: 'More planets = +5% production each. Send an expedition (costs coins + crew; some may die) to discover one. Add slots or build housing (+2 crew capacity per module).',
  planetsRules: 'You start with one planet. Each planet has a limited number of slots for upgrades (and housing).\n\n- Each extra planet gives +5% production (stacking).\n- To get a new planet: send an expedition. It costs coins and crew; each astronaut has a chance to die. If at least one survives, you discover the planet. Pilots guarantee one survivor.\n- Add slots to a planet (costs coins) or build housing there: each housing module uses 1 slot and adds +2 to your total crew capacity.',
  housing: 'Housing',
  housingHint: 'Build housing on a planet to increase crew capacity (+2 astronauts per module). Each module uses 1 slot on that planet.',
  housingNoSlot: 'No free slot on any planet. Add a slot or use slots for upgrades.',
  housingBuilt: 'built',
  housingBuildTooltip: 'Build housing on {{planet}}: {{cost}} ⬡ · uses 1 slot · +{{capacity}} crew capacity.',
  needCoinsForHousing: 'Need {{cost}} ⬡ to build housing.',
  buildHousingBtn: 'Build housing ({{cost}} ⬡)',
  buyNewPlanet: 'Send expedition',
  upgrades: 'Upgrades',
  upgradesHint: 'Buy upgrades to boost production; each uses one slot on a planet. Some cost crew. Add slots or new planets to place more.',
  upgradesRules: 'Upgrades increase your production (coins per second). Each planet has a limited number of slots (6 on the first planet).\n\n- You can buy the same upgrade multiple times; each copy uses one slot on the planet you choose.\n- Some upgrades also cost crew: when you buy them, that many astronauts are assigned to equipment (see Crew section).\n- To place more upgrades: add slots to a planet or discover new planets.',
  research: 'Scientific Research',
  researchHint: 'Unlock nodes for +% production and +% click. Each attempt costs coins and has a success chance; scientists boost it. Resets on Prestige.',
  researchRules: 'The research tree unlocks permanent bonuses (+% production, +% click, and effects like "this upgrade no longer costs crew").\n\n- Unlock nodes by attempting them: each attempt costs coins and has a success chance. If it fails, the coins are lost and you can try again.\n- Scientists in your crew increase the success chance (capped).\n- All research progress resets on Prestige.',
  invalidSaveFile: 'Invalid save file.',
  offlineIndicator: 'You are offline. Progress may not be saved.',
  reducedMotion: 'Reduce motion',
  theme: 'Theme',
  themeLight: 'Light',
  themeDark: 'Dark',
  soundEnabled: 'Sound effects',
  debug: 'Debug',
  closeDebug: 'Close debug',

  starfieldSpeedSlow: 'Slow',
  starfieldSpeedNormal: 'Normal',
  starfieldSpeedFast: 'Fast',
  debugTriggerEvent: 'Trigger event',
  debugClearEvents: 'Clear events',
  debugF3Hint: 'F3 to toggle',
  firstPrestigeToast: 'First prestige!',
  firstUpgradeToast: 'First upgrade!',
  firstNewPlanetToast: 'First new planet!',
  firstAstronautToast: 'First astronaut!',
  expeditionDiscoveredWithDeaths: 'Discovered {{name}}! {{survivors}} astronaut(s) returned. {{deaths}} lost.',
  expeditionDiscoveredAllReturned: 'Discovered {{name}}! All {{survivors}} astronaut(s) returned.',
  expeditionFailed: 'Expedition failed. All {{n}} astronaut(s) lost. Planet not discovered.',
  chartLegendCoins: 'Coins ⬡',
  chartLegendProduction: 'Production /s',
  chartLegendTotalEver: 'Total ever ⬡',
  chartLegendCoinsGained: 'Gained ⬡',
  chartLegendCoinsPerClick: '⬡/click',
  chartLegendMinMaxPlaceholder: 'Min — · Max —',
  coinsGainedPerPeriod: 'Coins gained (per period)',
  coinsPerClickPerPeriod: 'Coins per click (per period)',
  chartAriaCoinsGained: 'Coins gained per period line chart. Hover to see values.',
  chartAriaCoinsPerClickPerPeriod: 'Average coins per click per period. Hover to see values.',
  chartDescCoins: 'Your current coin balance at each sample time. Goes up with production and clicks, down when you spend.',
  chartDescProduction: 'Empire production rate (coins per second) at each sample. Affected by upgrades, planets, prestige, events.',
  chartDescTotalEver: 'Cumulative coins earned since the start of the game. Never decreases.',
  chartDescCoinsGained: 'Coins earned in each time window (between two samples). Spikes when you earn a lot in a short time.',
  chartDescCoinsPerClickPerPeriod: 'In each time window: average coins earned per mine click. Rises with prestige, research, and events—shows how strong your clicks are over time.',
  chartDescClicksPerPeriod: 'Number of mine clicks in each time window. Shows how active you were in that period.',
  chartDescCoinsFromClicksPerPeriod: 'Coins earned from mine clicks only (no production) in each time window.',
  clicksPerPeriod: 'Clicks (per period)',
  coinsFromClicksPerPeriod: 'Coins from clicks (per period)',
  chartLegendClicks: 'Clicks',
  chartLegendCoinsFromClicks: 'From clicks ⬡',
  chartAriaClicks: 'Clicks per period line chart. Hover to see values.',
  chartAriaCoinsFromClicks: 'Coins from clicks per period line chart. Hover to see values.',
  achievementLockedTitle: '???',
  achievementSecret: '???',
  lastSavedJustNow: 'Saved',
  lastSavedAgo: 'Saved {{time}} ago',
  lastSavedSecs: '{{n}}s',
  lastSavedMins: '{{n}}m',
  researchFailedTryAgain: 'Research failed. Try again.',
  researching: 'Researching...',
  unknownResearch: 'Unknown research.',
  prerequisitesNotMet: 'Prerequisites not met or already unlocked.',
  notEnoughCoins: 'Not enough coins.',
  researchFailedCoinsSpent: 'Research failed. Coins spent. Try again.',
  researchRequires: 'Requires: {{names}}',
  researchSlotFree: '{{n}} upgrade(s) no longer use a slot',
  researchCrewFree: '{{n}} upgrade(s) no longer require crew',
  researchUpgradeNoSlot: '{{name}}: no longer uses a slot',
  researchUpgradeNoCrew: '{{name}}: no longer requires crew',
  researchUpgradeLessSlot: '{{name}}: uses {{n}} less slot(s)',
  researchUpgradeLessCrew: '{{name}}: requires {{n}} less crew',
  researchUnlockPath: 'Unlock path: {{path}}',
  researchUnlockPathSingle: 'Unlock path: {{name}}',
  researchEffectsLabel: 'Effects:',
  researchInfoTitle: 'Research details',
  researchAttemptTooltip: 'Attempt ({{pct}}% success). On failure, coins are lost.',
  researchAttemptDisabled: 'Complete prerequisites and have enough coins.',
  researchSuccessFormat: '{{name}} complete! {{mods}}.',
  attempt: 'Attempt',
  percentSuccess: '{{pct}}% success',
  claimRewardFormat: 'Claim {{reward}} ⬡',
  completeQuestToClaim: 'Complete the quest to claim the reward',
  questStreakKeep: 'Streak ×{{n}} · claim next within 5 min to keep it',
  streakExpired: 'Streak expired. Claim a quest to start a new streak.',
  achievementToast: 'Achievement: {{name}}',
  welcomeBack: 'Welcome back! +{{coins}} coins while you were away.',
  welcomeBackCapped: 'Welcome back! +{{coins}} coins while you were away (capped at 12h).',
  welcomeBackWithHours: 'You earned {{coins}} coins while away ({{hours}} h).',
  welcomeBackCappedWithHours: 'You earned {{coins}} coins while away ({{hours}} h, capped at 12h).',
  luckyToast: '★ LUCKY! +{{coins}} ⬡',
  questStreakToastFormat: 'Quest streak ×{{n}}! +{{pct}}% reward',
  milestoneToastFormat: 'Milestone: {{coins}} total coins earned!',
  dailyBonusToastFormat: 'Daily bonus: +{{n}} ⬡',
  criticalToastFormat: 'CRITICAL! +{{coins}} ⬡',
  prestigeMilestoneToastFormat: 'Prestige level {{level}}! +{{pct}}% production forever',
  crewStatFormat: 'Crew: {{n}} astronaut(s) available',
  crewStatDetail: '{{assigned}} on equipment · {{total}} total',
  crewStatByJob: '{{miners}} miners, {{scientists}} scientists, {{pilots}} pilots',
  crewStatRoleMiners: 'miners',
  crewStatRoleScientists: 'scientists',
  crewStatRolePilots: 'pilots',
  breakdownBase: 'Empire',
  breakdownPlanets: 'planets',
  breakdownPrestige: 'prestige',
  breakdownCrew: 'crew',
  breakdownResearch: 'research',
  breakdownEvent: 'event',
  nextMilestoneFormat: '{{remaining}} ⬡ to unlock {{title}}',
  toUnlock: 'to unlock',
  nextEventLabel: 'Next event',
  nextEventInFormat: 'Next event in {{time}}',
  eventBadgeTitle: '{{name}}: ×{{mult}} production',
  eventsHintTitle: 'Events you have seen',
  eventsHintWhat: 'Random events temporarily boost or reduce your production (e.g. ×2 for 30s). They unlock at 50,000 coins.',
  eventsHintHeading: 'Events you\'ve encountered',
  eventsHintEmpty: 'None yet. They will appear here once they occur.',
  eventsHintUnlock: 'Unlock events at 50,000 coins.',
  collapseSection: 'Collapse',
  expandSection: 'Expand',
  statisticsTitle: 'Statistics',
  statisticsHint: 'Charts and stats (economy, activity, run). Data is saved across sessions.',
  statisticsRules: 'Charts and stats for your mining empire. Data is saved across sessions.\n\n- Economy: coins over time, production rate, total coins ever.\n- Activity: clicks per period, coins earned from clicks — see how much you gain from clicking vs passive production.\n- Run stats: duration, coins earned, quests claimed, events, best combo. Resets on Prestige.',
  statisticsIntro: 'Track your mining empire: economy, progression, and activity. Chart data is saved across sessions.',
  chartsTitle: 'Charts',
  lastXMin: 'Last {{n}} min',
  lastXHours: 'Last {{n}} h',
  coinsOverTime: 'Coins over time',
  productionOverTime: 'Production over time',
  totalCoinsEverChart: 'Total coins ever',
  economyTitle: 'Economy',
  productionBreakdownTitle: 'Production breakdown',
  progressionTitle: 'Progression',
  activityTitle: 'Activity',
  runStatsTitle: 'This run',
  runDuration: 'Run duration',
  runCoinsEarned: 'Coins earned',
  runQuestsClaimed: 'Quests claimed',
  runEventsTriggered: 'Events triggered',
  runMaxCombo: 'Best combo (run)',
  runAvgCoinsPerSec: 'Avg coins/s (run)',
  questsEventsTitle: 'Quests & events',
  achievementsTitle: 'Achievements',
  currentCoins: 'Current coins',
  productionEffective: 'Production (effective)',
  totalCoinsEverLabel: 'Total coins ever',
  avgCoinsPerClick: 'Avg coins per click (session)',
  baseRate: 'Empire rate',
  planetBonus: 'Planet bonus',
  prestigeBonus: 'Prestige bonus',
  crewBonus: 'Crew bonus',
  eventMultiplier: 'Event multiplier',
  researchBonus: 'Research bonus',
  planetsCount: 'Planets',
  upgradesOwned: 'Upgrades owned',
  slotsUsedTotal: 'Slots used / total',
  prestigeLevel: 'Prestige level',
  prestigesToday: 'Prestiges today',
  researchNodesUnlocked: 'Research nodes',
  expeditionStatus: 'Expedition',
  expeditionStatInProgress: 'In progress ({{s}}s)',
  expeditionStatNone: '—',
  crewFree: 'Crew (free)',
  crewAssigned: 'Crew (assigned)',
  clicksLifetime: 'Clicks (lifetime)',
  clicksSession: 'Clicks (this session)',
  coinsFromClicksSession: 'Coins from clicks (session)',
  totalPlayTime: 'Total play time',
  sessionDuration: 'Session duration',
  playingSince: 'Playing since',
  peakProductionChart: 'Peak production (chart)',
  questStreak: 'Quest streak',
  activeEvents: 'Active events',
  nextEventIn: 'Next event in',
  unlockedLabel: 'Unlocked',
  chartMinMax: 'Min {{min}} · Max {{max}}',
  chartAriaCoins: 'Coins over time line chart. Hover to see values.',
  chartAriaProduction: 'Production over time line chart. Hover to see values.',
  chartAriaTotalEver: 'Total coins ever line chart. Hover to see values.',
  upgradeGroupEarly: 'Early',
  upgradeGroupMid: 'Mid',
  upgradeGroupLate: 'Late',
  buyLabel: 'Buy',
  buyLabelPlusOne: '+1',
  maxLabel: 'Max',
  maxLabelCount: 'Max ({{n}})',
  recommended: 'Recommended',
  needAstronauts: 'Need {{n}} astronaut(s). Hire crew in the Crew section.',
  noFreeSlot: 'No free slot. Add a slot to a planet or buy a new planet!',
  needCoinsAndSlot: 'Need {{cost}} and a free slot.',
  buyUpgradeTitle: 'Buy {{name}} · {{cost}}',
  needCrewToBuy: 'Need more crew to buy this upgrade.',
  needCoinsForOne: 'Need {{cost}} to buy at least one.',
  noSlotsOrCoins: 'No free slots or not enough coins/crew to buy more.',
  toPlanet: 'To',
  assignToPlanet: 'Assign to planet',
  tierLabel: 'Tier {{n}}',
  crewBadgeTitle: 'Cost in astronauts (spent when you buy)',
  crewCostShort: '{{n}} crew',
  upgradeUsesSlot: '1 slot',
  upgradeNoSlot: 'No slot',
  upgradePlanetAffinityTitle: 'Production by planet type',
  slots: 'slots',
  addSlotBtn: '+1 slot · {{cost}} ⬡',
  addSlotTooltip: 'Add one upgrade slot · {{cost}} ⬡',
  needCoinsForSlot: 'Need {{cost}} ⬡ to add a slot',
  sendExpeditionBtn: 'Send expedition ({{cost}} ⬡ + {{n}} crew)',
  sendExpeditionTooltip: 'Send {{n}} astronauts on expedition. Risk: some may die (25% each). If all die, planet not discovered. Cost: {{cost}} ⬡',
  needForExpedition: 'Need {{cost}} ⬡ and {{n}} astronauts to launch expedition',
  expeditionInProgress: 'Expedition in progress… {{seconds}}s remaining',
  planetCardTitle: '{{used}}/{{max}} slots',
  planetCardTitleProd: '{{used}}/{{max}} slots · +{{pct}}% prod from planets',
  planetInfoType: 'Type',
  planetInfoSlots: 'Slots',
  planetInfoProduction: 'Production',
  planetInfoHousing: 'Housing',
  planetInfoHousingLine: '{{n}} module(s) · +{{crew}} crew capacity',
  planetInfoEquipment: 'Equipment',
  planetInfoTitle: 'Planet info',
  hireAstronautCost: 'Hire astronaut · {{cost}} ⬡',
  hireAsRole: '{{role}} · {{cost}} ⬡',
  crewRoleMiner: 'Miner',
  crewRoleScientist: 'Scientist',
  crewRolePilot: 'Pilot',
  crewRoleMinerHint: '+2% production each',
  crewRoleScientistHint: '+2% research success chance each (capped)',
  crewRolePilotHint: 'Guarantees at least one survivor on expedition',
  crewVeterans: '{{n}} veteran(s) · +0.5% production each',
  crewBreakdown: '{{miners}} miners, {{scientists}} scientists, {{pilots}} pilots',
  noCrewYetMax: 'No crew yet (max {{max}})',
  crewLineAssigned: '{{assigned}} on equipment · 0 free (hire more for +% or discover planets to raise cap)',
  crewLineFree: '{{free}} free · +{{pct}}% production | {{assigned}} on equipment ({{total}}/{{max}})',
  crewLineAstronauts: '{{free}}/{{max}} astronaut(s) · +{{pct}}% production',
  crewSummary: '{{current}}/{{max}} astronauts · +{{pct}}% from crew',
  crewSummaryWithAssigned: '{{free}} free · {{assigned}} on equipment → {{total}}/{{max}} · +{{pct}}% from crew',
  crewSummaryNoBonus: '{{current}}/{{max}} astronauts',
  crewSummaryNoBonusWithAssigned: '{{free}} free · {{assigned}} on equipment → {{total}}/{{max}}',
  crewRoleEffectMiner: '+{{pct}}% production',
  crewRoleEffectScientist: '+{{pct}}% research success',
  crewRoleEffectPilot: '1 survivor guaranteed',
  crewInModules: '{{n}} astronaut(s) are on equipment — they were assigned when you bought upgrades that cost crew.',
  crewSegmentRole: '{{n}} {{role}}',
  crewSegmentEquipment: '{{n}} on equipment',
  crewSegmentFree: '{{n}} free slot(s)',
  crewOperatesHint: 'Hire crew to buy tier 3+ upgrades (each costs coins + astronauts).',
  crewOperatesNext: '{{free}} available. Next: {{name}} costs {{n}} crew.',
  crewOperatesUpgrades: '{{n}} upgrade(s) operated by crew.',
  crewOperatesAvailable: '{{free}} available.',
  freeAstronautsTitle: 'Free astronauts: +2% production each (miners). Others: scientists (research), pilots (expedition survivor). Max: {{max}}.',
  prestigeConfirmDescLevel: "You'll reset to 0 coins and 1 planet. You keep Prestige level {{level}} (+{{pct}}% production forever).",
  prestigeConfirmAfter: 'After Prestige: level {{level}} → +{{pct}}% production forever.',
  prestigeRewardsTitle: 'Prestige rewards',
  prestigeRewardsIntro: 'What you gain at each prestige level:',
  prestigeReward1: 'Prestige 1: +4% production forever. Unlocks all click bonuses: Lucky / Super Lucky / Critical clicks, Combo multiplier, and Research +% click (skill tree). Before prestige 1, each click gives only 1 coin.',
  prestigeRewardLevelFormat: 'Prestige {{level}}: +{{prod}}% production. Unlocks: +{{click}}% click forever.',
  prestigeRewardsWhatFor: 'What do I get?',
  eachPerSecond: '+{{n}} /s each',
  totalPerSecond: 'Total: +{{n}}/s',
  needCoinsToBuy: 'Need {{cost}}{{crew}} to buy.',
  needCoinsAndCrew: 'Need {{cost}} + {{crew}} and a free slot.',
  maxBuyTooltip: 'Buy as many as you can afford with current slots',
  locked: 'Locked',
  debugCoinsRaw: 'Coins (raw)',
  debugProductionBase: 'Production (base)',
  debugProductionEffective: 'Production (effective)',
  debugEventMult: 'Event mult',
  debugPrestigeLevel: 'Prestige level',
  debugPlanets: 'Planets',
  debugUpgradesTotal: 'Upgrades total',
  debugNextEventIn: 'Next event in',
  debugActiveEvents: 'Active events',
  progressionWelcomeTitle: 'Welcome to Stellar Miner',
  progressionWelcomeBody: 'Click the asteroid (or press Space) to mine coins. Your goal: grow your mining operation by buying upgrades, hiring crew, and expanding to new planets. Start by mining until you can afford your first upgrade!',
  progressionUpgradesTitle: 'Upgrades',
  progressionUpgradesBody: 'Spend coins to buy equipment that produces coins automatically. Each upgrade adds production per second. You can buy the same upgrade multiple times—each goes on a planet slot. Start with a Mining Robot (45 ⬡).',
  progressionCrewTitle: 'Crew',
  progressionCrewBody: 'Hire astronauts to boost your production (+2% per astronaut). Better upgrades require crew to operate—you spend astronauts when you buy those upgrades. Hire your first astronaut when you can afford it (2,500 ⬡).',
  progressionQuestTitle: 'Quests',
  progressionQuestBody: 'Complete quests for bonus coins and rewards. Each quest has a target (e.g. mine X coins, buy upgrades). Claim within 5 minutes of completion for a streak bonus. Check the Quest section above.',
  progressionPlanetsTitle: 'Planets',
  progressionPlanetsBody: 'Send astronauts on expeditions to discover new planets (+5% production each). Some may die during the mission; if all die, the planet is not discovered. You can also add slots to existing planets.',
  progressionEventsTitle: 'Random events',
  progressionEventsBody: 'Space is full of surprises. Random events will now occasionally boost or reduce your production for a short time. Watch the event badges and plan around them!',
  progressionResearchTitle: 'Scientific Research',
  progressionResearchBody: 'Skill tree: attempt to unlock nodes for +% production and +% click. Each attempt can succeed or fail (coins lost on failure). Resets on Prestige.',
  progressionPrestigeTitle: 'Prestige',
  progressionPrestigeBody: 'When you reach 5,000,000 coins you can Prestige: reset coins and planets to gain +4% production per prestige level forever. Use it to progress faster on each new run.',
  versionLabel: 'Version',
  changelog: 'Changelog',
  whatsNew: "What's new",
  updateAvailable: 'New update',
  newUpdateAvailable: 'A new version is available. Open settings to see what\'s new.',
  infoTitle: "What's new",
  infoVersionLabel: 'Version',
} as const;

const stringsFr: Record<keyof typeof stringsEn, string> = {
  appTitle: 'STELLAR MINER',
  appSubtitle: 'Minez des pièces. Achetez des améliorations. Conquérez la ceinture.',
  settings: 'Paramètres',
  openSettings: 'Ouvrir les paramètres',
  close: 'Fermer',
  language: 'Langue',
  languageEn: 'English',
  languageFr: 'Français',
  starfieldSpeed: 'Vitesse du champ d’étoiles',
  showOrbitLines: 'Afficher les orbites',
  clickParticles: 'Particules au clic',
  compactNumbers: 'Nombres compacts (1,2K)',
  spaceKeyRepeat: 'Répétition de la touche Espace (maintenir pour miner)',
  layout: 'Disposition',
  layoutTabs: 'Onglets',
  layoutOnePage: 'Une page',
  pauseWhenBackground: 'Pause de la production quand l’onglet est en arrière-plan',
  exportSave: 'Exporter la sauvegarde',
  importSave: 'Importer la sauvegarde',
  exportSaveTitle: 'Copier la sauvegarde et télécharger en fichier',
  importSaveTitle: 'Charger une sauvegarde (remplace la partie en cours).',
  achievements: 'Succès',
  resetProgress: 'Réinitialiser la progression',
  resetConfirmTitle: 'Réinitialiser la progression ?',
  resetConfirmDesc: 'Pièces, planètes, améliorations, équipage et toute la progression seront perdus. Irréversible.',
  cancel: 'Annuler',
  resetAll: 'Tout réinitialiser',
  prestigeConfirmTitle: 'Prestige ?',
  prestigeConfirmDesc: 'Vous repartez à 0 pièce et 1 planète. Vous gardez le niveau Prestige et +4 % de production par niveau.',
  prestige: 'Prestige',
  gotIt: 'Compris',
  coins: 'Pièces',
  coinsTitle: 'Vos pièces. Dépensez-les en améliorations, équipage et planètes.',
  production: 'Production',
  productionTitle: 'Empire × planètes × prestige × événements',
  gameSections: 'Sections du jeu',
  tabsMoreLabel: 'Plus de sections',
  tabMine: 'Mine',
  tabDashboard: 'Tableau de bord',
  tabBase: 'Empire',
  tabResearch: 'Recherche',
  tabUpgrades: 'Améliorations',
  tabStats: 'Stats',
  dashboardTitle: 'Tableau de bord',
  dashboardOverview: 'Vue d’ensemble',
  dashboardQuickActions: 'Actions rapides',
  dashboardQuestReady: 'Quête à réclamer',
  dashboardPrestigeReady: 'Prestige disponible',
  dashboardExpeditionInProgress: 'Expédition en cours',
  dashboardNextMilestone: 'Prochain jalon',
  goToMine: 'Aller à Mine',
  goToEmpire: 'Aller à Empire',
  goToUpgrades: 'Aller aux Améliorations',
  goToResearch: 'Aller à Recherche',
  goToStats: 'Aller aux Stats',
  dashboardRecommended: 'À faire',
  dashboardRunSummary: 'Cette run',
  dashboardTimeTo: '~{{min}} min pour {{target}}',
  dashboardBuyOne: 'Acheter {{name}}',
  dashboardKeepMining: 'Continue à miner — onglet Mine pour gagner plus vite',
  dashboardStartResearch: 'Tenter une recherche : {{name}}',
  dashboardTimeToExpedition: '~{{min}} min pour l’expédition',
  dashboardShortcuts: 'Raccourcis',
  dashboardQuestsShort: 'quêtes',
  dashboardEventsShort: 'events',
  dashboardToPrestige: 'Vers Prestige',
  dashboardSolarSystems: 'Systèmes',
  mineZoneTitle: 'Cliquez ou Espace pour miner',
  keyboardShortcutsHint: 'Espace pour miner · 1–6 changer d’onglet',
  keyboardShortcutsSpaceKey: 'Espace',
  keyboardShortcutsMine: 'pour miner',
  keyboardShortcutsTabs: 'changer d’onglet',
  quest: 'Quête',
  questHint: 'Atteignez l’objectif puis réclamez. Réclamez sous 5 min pour enchaîner une série et booster la prochaine récompense.',
  questRules: 'Les quêtes vous donnent un objectif aléatoire (ex. « Gagner 50K pièces », « Avoir 10 astronautes »). Atteignez l’objectif, puis réclamez la récompense.\n\n- Réclamez dans les 5 minutes après avoir terminé pour enchaîner une série ; la prochaine récompense est augmentée.\n- Si vous attendez trop, la série repart à zéro.\n- Chaque nouvelle quête a un nouvel objectif et montant aléatoires.',
  claim: 'Récupérer',
  prestigeHint: 'Réinitialisez la run pour gagner +4 % production par niveau pour toujours. Se débloque au seuil de pièces indiqué.',
  prestigeRules: 'Le Prestige réinitialise votre run (pièces, planètes, améliorations, équipage, recherche) mais vous gardez votre niveau de Prestige pour toujours.\n\n- Chaque niveau donne +4 % de production sur toutes les runs suivantes (cumulable).\n- Il faut atteindre le seuil de pièces indiqué dans la section pour débloquer le bouton.\n- Utilisez-le quand la progression semble lente — le bonus permanent rendra la prochaine run plus rapide.',
  crew: 'Équipage',
  crewHint: 'Recrutez par rôle : mineurs +2 % production ; scientifiques +2 % succès recherche ; pilotes garantissent un survivant en expédition. Certaines améliorations coûtent du crew (assignés à l’équipement). Réinitialisé au Prestige.',
  crewRules: 'Les astronautes donnent des bonus et sont nécessaires pour acheter certaines améliorations. Tout ici est réinitialisé au Prestige.\n\nL’équipage libre (les chiffres dans les cartes) donne des bonus passifs :\n- Mineurs : +2 % production chacun.\n- Scientifiques : +2 % de chance de succès en recherche chacun (plafonné).\n- Pilotes : garantissent au moins un survivant en expédition.\n\nQuand vous achetez une amélioration qui coûte du crew, ces astronautes sont assignés à l’équipement — ils ne comptent plus comme « libres » mais font toujours partie du total. La capacité vient des planètes et de l’habitat (+2 par module). Les vétérans sont des survivants d’expédition et donnent +0,5 % production chacun.',
  crewRecruitLabel: 'Recruter',
  noCrewYet: 'Pas encore d’équipage',
  hireAstronaut: 'Engager un astronaute',
  planets: 'Planètes',
  planetsHint: 'Plus de planètes = +5 % production chacune. Envoyez une expédition (pièces + crew ; risque de mort) pour en découvrir. Ajoutez des emplacements ou construisez de l’habitat (+2 capacité crew par module).',
  planetsRules: 'Vous commencez avec une planète. Chaque planète a un nombre limité d’emplacements pour les améliorations (et l’habitat).\n\n- Chaque planète en plus donne +5 % de production (cumulable).\n- Pour avoir une nouvelle planète : envoyez une expédition. Elle coûte des pièces et du crew ; chaque astronaute a un risque de mourir. Si au moins un survit, vous découvrez la planète. Les pilotes garantissent un survivant.\n- Ajoutez des emplacements à une planète (coût en pièces) ou construisez de l’habitat : chaque module d’habitat utilise 1 emplacement et ajoute +2 à votre capacité d’équipage totale.',
  housing: 'Maison',
  housingHint: "Construisez une maison sur une planète pour augmenter la capacité d'équipage (+2 astronautes par module). Chaque module utilise 1 emplacement sur la planète.",
  housingNoSlot: 'Aucun emplacement libre sur les planètes. Ajoutez un emplacement ou utilisez-les pour des améliorations.',
  housingBuilt: 'construit(s)',
  housingBuildTooltip: "Construire une maison sur {{planet}} : {{cost}} ⬡ · 1 emplacement · +{{capacity}} capacité d'équipage.",
  needCoinsForHousing: 'Il faut {{cost}} ⬡ pour construire une maison.',
  buildHousingBtn: 'Construire une maison ({{cost}} ⬡)',
  buyNewPlanet: 'Envoyer une expédition',
  upgrades: 'Améliorations',
  upgradesHint: 'Achetez des améliorations pour la production ; chacune utilise un emplacement. Certaines coûtent du crew. Ajoutez des emplacements ou des planètes pour en placer plus.',
  upgradesRules: 'Les améliorations augmentent votre production (pièces par seconde). Chaque planète a un nombre limité d’emplacements (6 sur la première).\n\n- Vous pouvez acheter la même amélioration plusieurs fois ; chaque exemplaire utilise un emplacement sur la planète choisie.\n- Certaines améliorations coûtent aussi du crew : à l’achat, ces astronautes sont assignés à l’équipement (voir la section Équipage).\n- Pour placer plus d’améliorations : ajoutez des emplacements ou découvrez de nouvelles planètes.',
  research: 'Recherche scientifique',
  researchHint: 'Débloquez des nœuds pour + % production et + % clic. Chaque tentative coûte des pièces et a une chance de succès ; les scientifiques l’augmentent. Réinitialisé au Prestige.',
  researchRules: 'L’arbre de recherche débloque des bonus permanents (+ % production, + % clic, et des effets comme « cette amélioration ne coûte plus de crew »).\n\n- Débloquez les nœuds en les tentant : chaque tentative coûte des pièces et a une chance de succès. En cas d’échec, les pièces sont perdues et vous pouvez réessayer.\n- Les scientifiques dans votre équipage augmentent la chance de succès (plafonnée).\n- Toute la recherche est réinitialisée au Prestige.',
  invalidSaveFile: 'Fichier de sauvegarde invalide.',
  offlineIndicator: 'Vous êtes hors ligne. La progression peut ne pas être enregistrée.',
  reducedMotion: 'Réduire les animations',
  theme: 'Thème',
  themeLight: 'Clair',
  themeDark: 'Sombre',
  soundEnabled: 'Effets sonores',
  debug: 'Debug',
  closeDebug: 'Fermer le debug',

  starfieldSpeedSlow: 'Lent',
  starfieldSpeedNormal: 'Normal',
  starfieldSpeedFast: 'Rapide',
  debugTriggerEvent: 'Déclencher un événement',
  debugClearEvents: 'Effacer les événements',
  debugF3Hint: 'F3 pour afficher/masquer',
  firstPrestigeToast: 'Premier prestige !',
  firstUpgradeToast: 'Première amélioration !',
  firstNewPlanetToast: 'Première nouvelle planète !',
  firstAstronautToast: 'Premier astronaute !',
  expeditionDiscoveredWithDeaths: 'Découverte : {{name}} ! {{survivors}} astronaute(s) de retour. {{deaths}} perdu(s).',
  expeditionDiscoveredAllReturned: 'Découverte : {{name}} ! Tous les {{survivors}} astronaute(s) sont revenus.',
  expeditionFailed: 'Expédition échouée. Les {{n}} astronaute(s) ont péri. Planète non découverte.',
  chartLegendCoins: 'Pièces ⬡',
  chartLegendProduction: 'Production /s',
  chartLegendTotalEver: 'Total cumulé ⬡',
  chartLegendCoinsGained: 'Gagnées ⬡',
  chartLegendCoinsPerClick: '⬡/clic',
  chartLegendMinMaxPlaceholder: 'Min — · Max —',
  coinsGainedPerPeriod: 'Pièces gagnées (par période)',
  coinsPerClickPerPeriod: 'Pièces par clic (par période)',
  chartAriaCoinsGained: 'Graphique des pièces gagnées par période. Survolez pour voir les valeurs.',
  chartAriaCoinsPerClickPerPeriod: 'Moyenne de pièces par clic par période. Survolez pour voir les valeurs.',
  chartDescCoins: 'Votre solde de pièces à chaque prélèvement. Monte avec la production et les clics, baisse quand vous dépensez.',
  chartDescProduction: 'Taux de production de l\'empire (pièces par seconde) à chaque prélèvement. Dépend des améliorations, planètes, prestige, événements.',
  chartDescTotalEver: 'Pièces cumulées gagnées depuis le début. Ne baisse jamais.',
  chartDescCoinsGained: 'Pièces gagnées dans chaque fenêtre de temps (entre deux prélèvements). Monte en pic quand vous gagnez beaucoup en peu de temps.',
  chartDescCoinsPerClickPerPeriod: 'Dans chaque fenêtre : moyenne de pièces gagnées par clic mine. Monte avec le prestige, la recherche et les events—montre la puissance de tes clics dans le temps.',
  chartDescClicksPerPeriod: 'Nombre de clics mine dans chaque fenêtre de temps. Montre à quel point vous étiez actif.',
  chartDescCoinsFromClicksPerPeriod: 'Pièces gagnées uniquement par les clics mine (sans la production) dans chaque fenêtre.',
  clicksPerPeriod: 'Clics (par période)',
  coinsFromClicksPerPeriod: 'Pièces des clics (par période)',
  chartLegendClicks: 'Clics',
  chartLegendCoinsFromClicks: 'Des clics ⬡',
  chartAriaClicks: 'Graphique des clics par période. Survolez pour voir les valeurs.',
  chartAriaCoinsFromClicks: 'Graphique des pièces des clics par période. Survolez pour voir les valeurs.',
  achievementLockedTitle: '???',
  achievementSecret: '???',
  lastSavedJustNow: 'Sauvegardé',
  lastSavedAgo: 'Sauvegardé il y a {{time}}',
  lastSavedSecs: '{{n}} s',
  lastSavedMins: '{{n}} min',
  researchFailedTryAgain: 'Échec de la recherche. Réessayez.',
  researching: 'Recherche en cours…',
  unknownResearch: 'Recherche inconnue.',
  prerequisitesNotMet: 'Prérequis non remplis ou déjà débloqué.',
  notEnoughCoins: 'Pas assez de pièces.',
  researchFailedCoinsSpent: 'Échec. Les pièces sont perdues. Réessayez.',
  researchRequires: 'Requis : {{names}}',
  researchSlotFree: '{{n}} amélioration(s) n’utilisent plus d’emplacement',
  researchCrewFree: '{{n}} amélioration(s) ne nécessitent plus d’équipage',
  researchUpgradeNoSlot: '{{name}} : n’utilise plus d’emplacement',
  researchUpgradeNoCrew: '{{name}} : ne nécessite plus d’équipage',
  researchUpgradeLessSlot: '{{name}} : utilise {{n}} emplacement(s) de moins',
  researchUpgradeLessCrew: '{{name}} : nécessite {{n}} équipage en moins',
  researchUnlockPath: 'Parcours : {{path}}',
  researchUnlockPathSingle: 'Parcours : {{name}}',
  researchEffectsLabel: 'Effets :',
  researchInfoTitle: 'Détails de la recherche',
  researchAttemptTooltip: 'Tenter ({{pct}} % de succès). En cas d’échec, les pièces sont perdues.',
  researchAttemptDisabled: 'Remplissez les prérequis et ayez assez de pièces.',
  researchSuccessFormat: '{{name}} terminé ! {{mods}}.',
  attempt: 'Tenter',
  percentSuccess: '{{pct}} % de succès',
  claimRewardFormat: 'Récupérer {{reward}} ⬡',
  completeQuestToClaim: 'Terminez la quête pour récupérer la récompense.',
  questStreakKeep: 'Série ×{{n}} · réclamez la prochaine sous 5 min pour la garder.',
  streakExpired: 'Série expirée. Réclamez une quête pour en commencer une nouvelle.',
  achievementToast: 'Succès : {{name}}',
  welcomeBack: 'Bon retour ! +{{coins}} pièces pendant votre absence.',
  welcomeBackCapped: 'Bon retour ! +{{coins}} pièces pendant votre absence (plafonné 12 h).',
  welcomeBackWithHours: 'Vous avez gagné {{coins}} pièces pendant votre absence ({{hours}} h).',
  welcomeBackCappedWithHours: 'Vous avez gagné {{coins}} pièces pendant votre absence ({{hours}} h, plafonné 12 h).',
  luckyToast: '★ CHANCE ! +{{coins}} ⬡',
  questStreakToastFormat: 'Série de quêtes ×{{n}} ! +{{pct}} % de récompense',
  milestoneToastFormat: 'Jalon : {{coins}} pièces gagnées au total !',
  dailyBonusToastFormat: 'Bonus quotidien : +{{n}} ⬡',
  criticalToastFormat: 'CRITIQUE ! +{{coins}} ⬡',
  prestigeMilestoneToastFormat: 'Niveau prestige {{level}} ! +{{pct}} % de production pour toujours',
  crewStatFormat: 'Équipage : {{n}} astronaute(s) disponible(s)',
  crewStatDetail: '{{assigned}} sur l’équipement · {{total}} au total',
  crewStatByJob: '{{miners}} mineurs, {{scientists}} scientifiques, {{pilots}} pilotes',
  crewStatRoleMiners: 'mineurs',
  crewStatRoleScientists: 'scientifiques',
  crewStatRolePilots: 'pilotes',
  breakdownBase: 'Empire',
  breakdownPlanets: 'planètes',
  breakdownPrestige: 'prestige',
  breakdownCrew: 'équipage',
  breakdownResearch: 'recherche',
  breakdownEvent: 'événement',
  nextMilestoneFormat: '{{remaining}} ⬡ pour débloquer {{title}}',
  toUnlock: 'pour débloquer',
  nextEventLabel: 'Prochain événement',
  nextEventInFormat: 'Prochain événement dans {{time}}',
  eventBadgeTitle: '{{name}} : ×{{mult}} production',
  eventsHintTitle: 'Événements que tu as vus',
  eventsHintWhat: 'Les événements aléatoires boostent ou réduisent ta production pendant un temps (ex. ×2 pendant 30 s). Ils se débloquent à 50 000 pièces.',
  eventsHintHeading: 'Événements déjà vécus',
  eventsHintEmpty: 'Aucun pour l\'instant. Ils s\'afficheront ici quand tu en auras vus.',
  eventsHintUnlock: 'Débloque les événements à 50 000 pièces.',
  collapseSection: 'Replier',
  expandSection: 'Déplier',
  statisticsTitle: 'Statistiques',
  statisticsHint: 'Graphiques et stats (économie, activité, run). Données conservées entre les sessions.',
  statisticsRules: 'Graphiques et stats de votre empire minier. Les données sont conservées entre les sessions.\n\n- Économie : pièces dans le temps, taux de production, total de pièces. Activité : clics par période, pièces gagnées par les clics — pour voir ce que rapportent les clics vs la production passive.\n- Stats de run : durée, pièces gagnées, quêtes réclamées, événements, meilleur combo. Réinitialisées au Prestige.',
  statisticsIntro: 'Suivez votre empire minier : économie, progression et activité. Les graphiques sont conservés entre les sessions.',
  chartsTitle: 'Graphiques',
  lastXMin: 'Dernières {{n}} min',
  lastXHours: 'Dernières {{n}} h',
  coinsOverTime: 'Pièces dans le temps',
  productionOverTime: 'Production dans le temps',
  totalCoinsEverChart: 'Total des pièces',
  economyTitle: 'Économie',
  productionBreakdownTitle: 'Détail de la production',
  progressionTitle: 'Progression',
  activityTitle: 'Activité',
  runStatsTitle: 'Cette run',
  runDuration: 'Durée de la run',
  runCoinsEarned: 'Pièces gagnées',
  runQuestsClaimed: 'Quêtes réclamées',
  runEventsTriggered: 'Événements déclenchés',
  runMaxCombo: 'Meilleur combo (run)',
  runAvgCoinsPerSec: 'Moy. pièces/s (run)',
  questsEventsTitle: 'Quêtes et événements',
  achievementsTitle: 'Succès',
  currentCoins: 'Pièces actuelles',
  productionEffective: 'Production (effective)',
  totalCoinsEverLabel: 'Total des pièces',
  avgCoinsPerClick: 'Moy. pièces par clic (session)',
  baseRate: 'Taux empire',
  planetBonus: 'Bonus planètes',
  prestigeBonus: 'Bonus prestige',
  crewBonus: 'Bonus équipage',
  eventMultiplier: 'Multiplicateur événement',
  researchBonus: 'Bonus recherche',
  planetsCount: 'Planètes',
  upgradesOwned: 'Améliorations possédées',
  slotsUsedTotal: 'Emplacements utilisés / total',
  prestigeLevel: 'Niveau prestige',
  prestigesToday: 'Prestiges aujourd\'hui',
  researchNodesUnlocked: 'Nœuds recherche',
  expeditionStatus: 'Expédition',
  expeditionStatInProgress: 'En cours ({{s}} s)',
  expeditionStatNone: '—',
  crewFree: 'Équipage (libre)',
  crewAssigned: 'Équipage (assigné)',
  clicksLifetime: 'Clics (total)',
  clicksSession: 'Clics (cette session)',
  coinsFromClicksSession: 'Pièces des clics (session)',
  totalPlayTime: 'Temps de jeu total',
  sessionDuration: 'Durée de la session',
  playingSince: 'Joue depuis',
  peakProductionChart: 'Pic production (graphique)',
  questStreak: 'Série de quêtes',
  activeEvents: 'Événements actifs',
  nextEventIn: 'Prochain événement dans',
  unlockedLabel: 'Débloqués',
  chartMinMax: 'Min {{min}} · Max {{max}}',
  chartAriaCoins: 'Graphique des pièces dans le temps. Survolez pour voir les valeurs.',
  chartAriaProduction: 'Graphique de la production dans le temps. Survolez pour voir les valeurs.',
  chartAriaTotalEver: 'Graphique du total des pièces. Survolez pour voir les valeurs.',
  upgradeGroupEarly: 'Début',
  upgradeGroupMid: 'Milieu',
  upgradeGroupLate: 'Fin',
  buyLabel: 'Acheter',
  buyLabelPlusOne: '+1',
  maxLabel: 'Max',
  maxLabelCount: 'Max ({{n}})',
  recommended: 'Recommandé',
  needAstronauts: 'Il faut {{n}} astronaute(s). Engagez-en dans la section Équipage.',
  noFreeSlot: 'Aucun emplacement libre. Ajoutez un emplacement ou achetez une planète !',
  needCoinsAndSlot: 'Il faut {{cost}} et un emplacement libre.',
  buyUpgradeTitle: 'Acheter {{name}} · {{cost}}',
  needCrewToBuy: 'Il faut plus d’équipage pour acheter cette amélioration.',
  needCoinsForOne: 'Il faut {{cost}} pour en acheter au moins un.',
  noSlotsOrCoins: 'Pas d’emplacement libre ou pas assez de pièces/équipage.',
  toPlanet: 'Vers',
  assignToPlanet: 'Assigner à la planète',
  tierLabel: 'Niveau {{n}}',
  crewBadgeTitle: 'Coût en astronautes (dépensés à l’achat)',
  crewCostShort: '{{n}} équipage',
  upgradeUsesSlot: '1 emplacement',
  upgradeNoSlot: 'Aucun emplacement',
  upgradePlanetAffinityTitle: 'Production selon le type de planète',
  slots: 'emplacements',
  addSlotBtn: '+1 emplacement · {{cost}} ⬡',
  addSlotTooltip: 'Ajouter un emplacement d’amélioration · {{cost}} ⬡',
  needCoinsForSlot: 'Il faut {{cost}} ⬡ pour ajouter un emplacement',
  sendExpeditionBtn: 'Envoyer une expédition ({{cost}} ⬡ + {{n}} équipage)',
  sendExpeditionTooltip: 'Envoyez {{n}} astronautes en expédition. Risque : certains peuvent mourir (25 % chacun). Si tous meurent, la planète n’est pas découverte. Coût : {{cost}} ⬡',
  needForExpedition: 'Il faut {{cost}} ⬡ et {{n}} astronautes pour lancer l’expédition',
  expeditionInProgress: 'Expédition en cours… {{seconds}} s restantes',
  planetCardTitle: '{{used}}/{{max}} emplacements',
  planetCardTitleProd: '{{used}}/{{max}} emplacements · +{{pct}} % prod. planètes',
  planetInfoType: 'Type',
  planetInfoSlots: 'Emplacements',
  planetInfoProduction: 'Production',
  planetInfoHousing: 'Habitat',
  planetInfoHousingLine: '{{n}} module(s) · +{{crew}} capacité équipage',
  planetInfoEquipment: 'Équipement',
  planetInfoTitle: 'Infos planète',
  hireAstronautCost: 'Engager un astronaute · {{cost}} ⬡',
  hireAsRole: '{{role}} · {{cost}} ⬡',
  crewRoleMiner: 'Mineur',
  crewRoleScientist: 'Scientifique',
  crewRolePilot: 'Pilote',
  crewRoleMinerHint: '+2 % production chacun',
  crewRoleScientistHint: '+2 % chance de succès recherche chacun (plafonné)',
  crewRolePilotHint: 'Garantit au moins un survivant en expédition',
  crewVeterans: '{{n}} vétéran(s) · +0,5 % production chacun',
  crewBreakdown: '{{miners}} mineurs, {{scientists}} scientifiques, {{pilots}} pilotes',
  noCrewYetMax: 'Pas encore d’équipage (max {{max}})',
  crewLineAssigned: '{{assigned}} sur l’équipement · 0 libre',
  crewLineFree: '{{free}} libre · +{{pct}} % production | {{assigned}} sur l’équipement ({{total}}/{{max}})',
  crewLineAstronauts: '{{free}}/{{max}} astronaute(s) · +{{pct}} % production',
  crewSummary: '{{current}}/{{max}} astronautes · +{{pct}} % d’équipage',
  crewSummaryWithAssigned: '{{free}} libres · {{assigned}} sur l’équipement → {{total}}/{{max}} · +{{pct}} %',
  crewSummaryNoBonus: '{{current}}/{{max}} astronautes',
  crewSummaryNoBonusWithAssigned: '{{free}} libres · {{assigned}} sur l’équipement → {{total}}/{{max}}',
  crewRoleEffectMiner: '+{{pct}} % production',
  crewRoleEffectScientist: '+{{pct}} % succès recherche',
  crewRoleEffectPilot: '1 survivant garanti',
  crewInModules: '{{n}} astronaute(s) sont sur l’équipement — ils ont été assignés quand vous avez acheté des améliorations qui coûtaient du crew.',
  crewSegmentRole: '{{n}} {{role}}',
  crewSegmentEquipment: '{{n}} sur l’équipement',
  crewSegmentFree: '{{n}} emplacement(s) libre(s)',
  crewOperatesHint: 'Engagez de l’équipage pour acheter les améliorations niveau 3+ (pièces + astronautes).',
  crewOperatesNext: '{{free}} disponible(s). Prochaine : {{name}} coûte {{n}} équipage.',
  crewOperatesUpgrades: '{{n}} amélioration(s) opérée(s) par l’équipage.',
  crewOperatesAvailable: '{{free}} disponible(s).',
  freeAstronautsTitle: 'Astronautes libres : +2 % production (mineurs). Autres : scientifiques (recherche), pilotes (survivant expédition). Max : {{max}}.',
  prestigeConfirmDescLevel: 'Vous repartez à 0 pièce et 1 planète. Vous gardez le niveau Prestige {{level}} (+{{pct}} % production pour toujours).',
  prestigeConfirmAfter: 'Après Prestige : niveau {{level}} → +{{pct}} % production pour toujours.',
  prestigeRewardsTitle: 'Récompenses de prestige',
  prestigeRewardsIntro: 'Ce que vous gagnez à chaque niveau de prestige :',
  prestigeReward1: 'Prestige 1 : +4 % production pour toujours. Débloque tous les bonus de clic : Lucky / Super Lucky / Critical, multiplicateur Combo, et + % clic recherche (arbre). Avant le prestige 1, chaque clic ne donne qu’1 pièce.',
  prestigeRewardLevelFormat: 'Prestige {{level}} : +{{prod}} % production. Débloque : +{{click}} % clic pour toujours.',
  prestigeRewardsWhatFor: 'Qu’est-ce que je gagne ?',
  eachPerSecond: '+{{n}}/s chacun',
  totalPerSecond: 'Total : +{{n}}/s',
  needCoinsToBuy: 'Il faut {{cost}}{{crew}} pour acheter.',
  needCoinsAndCrew: 'Il faut {{cost}} + {{crew}} et un emplacement libre.',
  maxBuyTooltip: 'Acheter autant que possible avec les emplacements actuels',
  locked: 'Verrouillé',
  debugCoinsRaw: 'Pièces (brut)',
  debugProductionBase: 'Production (base)',
  debugProductionEffective: 'Production (effective)',
  debugEventMult: 'Mult. événement',
  debugPrestigeLevel: 'Niveau prestige',
  debugPlanets: 'Planètes',
  debugUpgradesTotal: 'Total améliorations',
  debugNextEventIn: 'Prochain événement dans',
  debugActiveEvents: 'Événements actifs',
  progressionWelcomeTitle: 'Bienvenue dans Stellar Miner',
  progressionWelcomeBody: 'Cliquez sur l’astéroïde (ou Espace) pour miner des pièces. Objectif : développer votre opération en achetant des améliorations, en engageant de l’équipage et en découvrant des planètes. Minez jusqu’à pouvoir vous offrir votre première amélioration !',
  progressionUpgradesTitle: 'Améliorations',
  progressionUpgradesBody: 'Dépensez des pièces pour acheter de l’équipement qui produit des pièces automatiquement. Chaque planète a un nombre limité d’emplacements (6 sur la première) : chaque robot ou foreuse en utilise un. Commencez par un Robot minier (45 ⬡), puis passez aux milliers, millions et au-delà.',
  progressionCrewTitle: 'Équipage',
  progressionCrewBody: 'Engagez des astronautes pour booster la production (+2 % par astronaute). Les meilleures améliorations nécessitent de l’équipage ; vous dépensez des astronautes à l’achat. Engagez votre premier astronaute quand vous pouvez (2 500 ⬡).',
  progressionQuestTitle: 'Quêtes',
  progressionQuestBody: 'Terminez des quêtes pour des pièces et récompenses bonus. Chaque quête a un objectif (ex. miner X pièces, acheter des améliorations). Réclamez sous 5 minutes pour un bonus de série.',
  progressionPlanetsTitle: 'Planètes',
  progressionPlanetsBody: 'Envoyez des astronautes en expédition pour découvrir de nouvelles planètes (+5 % production chacune). Certains peuvent mourir ; si tous meurent, la planète n’est pas découverte. Vous pouvez aussi ajouter des emplacements aux planètes existantes.',
  progressionEventsTitle: 'Événements aléatoires',
  progressionEventsBody: "L'espace réserve des surprises. Des événements aléatoires vont désormais parfois augmenter ou réduire ta production pendant un court moment. Surveille les badges d'événements !",
  progressionResearchTitle: 'Recherche scientifique',
  progressionResearchBody: 'Arbre de compétences : tentez de débloquer des nœuds pour + % production et + % clic. Chaque tentative peut réussir ou échouer (pièces perdues en cas d’échec). Réinitialisé au Prestige.',
  progressionPrestigeTitle: 'Prestige',
  progressionPrestigeBody: 'À 5 000 000 pièces vous pouvez Prestige : réinitialiser pièces et planètes pour +4 % de production par niveau de prestige pour toujours. Pour progresser plus vite à chaque run.',
  versionLabel: 'Version',
  changelog: 'Journal des modifications',
  whatsNew: 'Nouveautés',
  updateAvailable: 'Nouvelle mise à jour',
  newUpdateAvailable: 'Une nouvelle version est disponible. Ouvrez les paramètres pour voir les nouveautés.',
  infoTitle: 'Nouveautés',
  infoVersionLabel: 'Version',
};

export type StringKey = keyof typeof stringsEn;

const translations: Record<'en' | 'fr', Record<StringKey, string>> = {
  en: stringsEn,
  fr: stringsFr,
};

export function t(key: StringKey): string {
  const lang = getSettings().language ?? 'en';
  const bundle = translations[lang] ?? translations.en;
  return bundle[key] ?? stringsEn[key] ?? key;
}

/** Replace {{key}} placeholders in the translation for key. */
export function tParam(key: StringKey, params: Record<string, string | number>): string {
  let s = t(key);
  for (const [k, v] of Object.entries(params)) {
    s = s.replace(new RegExp(`\\{\\{${k}\\}\\}`, 'g'), String(v));
  }
  return s;
}

/** For backward compatibility: same keys as stringsEn. */
export const strings = stringsEn as Record<string, string>;

/** Update all elements with data-i18n attribute. Call on mount and when language changes. */
export function applyTranslations(): void {
  if (typeof document === 'undefined') return;
  document.querySelectorAll<HTMLElement>('[data-i18n]').forEach((el) => {
    const key = el.getAttribute('data-i18n');
    if (key && key in stringsEn) el.textContent = t(key as StringKey);
  });
  document.querySelectorAll<HTMLElement>('[data-i18n-title]').forEach((el) => {
    const key = el.getAttribute('data-i18n-title');
    if (key && key in stringsEn) el.title = t(key as StringKey);
  });
  document.querySelectorAll<HTMLElement>('[data-i18n-aria-label]').forEach((el) => {
    const key = el.getAttribute('data-i18n-aria-label');
    if (key && key in stringsEn) el.setAttribute('aria-label', t(key as StringKey));
  });
  const tabTitleKeys: Record<string, StringKey> = {
    mine: 'tabMine',
    dashboard: 'tabDashboard',
    empire: 'tabBase',
    research: 'tabResearch',
    upgrades: 'tabUpgrades',
    stats: 'tabStats',
  };
  document.querySelectorAll<HTMLElement>('.app-tab[data-tab]').forEach((btn) => {
    const tabId = btn.getAttribute('data-tab');
    const key = tabId ? tabTitleKeys[tabId] : null;
    if (key && key in stringsEn) btn.title = t(key);
  });
}
