/**
 * Centralized UI strings for i18n. Use t(key) in presentation layer.
 * Language from settings (en | fr).
 */
import { getSettings } from './gameState.js';

const stringsEn = {
  appTitle: 'STELLAR MINER',
  appSubtitle: 'Mine coins. Buy upgrades. Conquer the belt.',
  settings: 'Settings',
  openSettings: 'Open settings',
  close: 'Close',
  language: 'Language',
  languageEn: 'English',
  languageFr: 'Français',
  starfieldSpeed: 'Starfield speed',
  showOrbitLines: 'Show orbit lines',
  clickParticles: 'Click particles',
  compactNumbers: 'Compact numbers (1.2K)',
  spaceKeyRepeat: 'Allow Space key repeat (hold to mine)',
  layout: 'Layout',
  layoutTabs: 'Tabs',
  layoutOnePage: 'One page',
  pauseWhenBackground: 'Pause production when tab in background',
  exportSave: 'Export save',
  importSave: 'Import save',
  exportSaveTitle: 'Copy save to clipboard and download as file',
  importSaveTitle: 'Load a previously exported save (replaces current)',
  achievements: 'Achievements',
  resetProgress: 'Reset progress',
  resetConfirmTitle: 'Reset progress?',
  resetConfirmDesc: 'Coins, planets, upgrades, crew, achievements and all progress will be lost. This cannot be undone.',
  cancel: 'Cancel',
  resetAll: 'Reset all',
  prestigeConfirmTitle: 'Prestige?',
  prestigeConfirmDesc: "You'll reset to 0 coins and 1 planet. You keep your new Prestige level and +5% production per level forever.",
  prestige: 'Prestige',
  gotIt: 'Got it',
  coins: 'Coins',
  coinsTitle: 'Your current coins. Spend them on upgrades, crew, and planets.',
  production: 'Production',
  productionTitle: 'Base × planets × prestige × events',
  gameSections: 'Game sections',
  tabMine: 'Mine',
  tabBase: 'Base',
  tabResearch: 'Research',
  tabUpgrades: 'Upgrades',
  tabStats: 'Stats',
  mineZoneTitle: 'Click or press Space to mine',
  quest: 'Quest',
  claim: 'Claim',
  prestigeHint: 'Reset coins and planets to gain +5% production per prestige level forever.',
  crew: 'Crew',
  crewHint: 'Hire astronauts for +2% production each. Upgrades cost coins and astronauts (crew is assigned to operate the equipment). Resets on Prestige.',
  noCrewYet: 'No crew yet',
  hireAstronaut: 'Hire astronaut',
  planets: 'Planets',
  planetsHint: 'Each planet has upgrade slots (expandable). More planets = +5% production each. Send astronauts on an expedition to discover a new planet (some may die); if all survive or at least one returns, you discover it. Add slots to expand.',
  housing: 'Housing',
  housingHint: 'Build housing on a planet to increase crew capacity (+2 astronauts per module). Each module uses 1 slot on that planet.',
  housingNoSlot: 'No free slot on any planet. Add a slot or use slots for upgrades.',
  housingBuilt: 'built',
  housingBuildTooltip: 'Build housing on {{planet}}: {{cost}} ⬡ · uses 1 slot · +{{capacity}} crew capacity.',
  needCoinsForHousing: 'Need {{cost}} ⬡ to build housing.',
  buildHousingBtn: 'Build housing ({{cost}} ⬡)',
  buyNewPlanet: 'Send expedition',
  upgrades: 'Upgrades',
  upgradesHint: 'Each planet has a limited number of slots (6 on your first planet). You can buy each upgrade multiple times; each copy uses one slot. Add slots or discover new planets to place more.',
  research: 'Scientific Research',
  researchHint: 'Skill tree: attempt to unlock nodes for +% production and +% click. Each attempt has a success chance; on failure coins are lost. Resets on Prestige.',
  invalidSaveFile: 'Invalid save file.',
  offlineIndicator: 'You are offline. Progress may not be saved.',
  reducedMotion: 'Reduce motion',
  theme: 'Theme',
  themeLight: 'Light',
  themeDark: 'Dark',
  soundEnabled: 'Sound effects',
  debug: 'Debug',
  closeDebug: 'Close debug',

  starfieldSpeedSlow: 'Slow',
  starfieldSpeedNormal: 'Normal',
  starfieldSpeedFast: 'Fast',
  debugTriggerEvent: 'Trigger event',
  debugClearEvents: 'Clear events',
  debugF3Hint: 'F3 to toggle',
  firstPrestigeToast: 'First prestige!',
  firstUpgradeToast: 'First upgrade!',
  firstNewPlanetToast: 'First new planet!',
  firstAstronautToast: 'First astronaut!',
  expeditionDiscoveredWithDeaths: 'Discovered {{name}}! {{survivors}} astronaut(s) returned. {{deaths}} lost.',
  expeditionDiscoveredAllReturned: 'Discovered {{name}}! All {{survivors}} astronaut(s) returned.',
  expeditionFailed: 'Expedition failed. All {{n}} astronaut(s) lost. Planet not discovered.',
  chartLegendCoins: 'Coins ⬡',
  chartLegendProduction: 'Production /s',
  chartLegendTotalEver: 'Total ever ⬡',
  chartLegendMinMaxPlaceholder: 'Min — · Max —',
  achievementLockedTitle: '???',
  researchFailedTryAgain: 'Research failed. Try again.',
  researching: 'Researching...',
  unknownResearch: 'Unknown research.',
  prerequisitesNotMet: 'Prerequisites not met or already unlocked.',
  notEnoughCoins: 'Not enough coins.',
  researchFailedCoinsSpent: 'Research failed. Coins spent. Try again.',
  researchRequires: 'Requires: {{names}}',
  researchSlotFree: '{{n}} upgrade(s) no longer use a slot',
  researchCrewFree: '{{n}} upgrade(s) no longer require crew',
  researchUpgradeNoSlot: '{{name}}: no longer uses a slot',
  researchUpgradeNoCrew: '{{name}}: no longer requires crew',
  researchUpgradeLessSlot: '{{name}}: uses {{n}} less slot(s)',
  researchUpgradeLessCrew: '{{name}}: requires {{n}} less crew',
  researchUnlockPath: 'Unlock path: {{path}}',
  researchUnlockPathSingle: 'Unlock path: {{name}}',
  researchEffectsLabel: 'Effects:',
  researchInfoTitle: 'Research details',
  researchAttemptTooltip: 'Attempt ({{pct}}% success). On failure, coins are lost.',
  researchAttemptDisabled: 'Complete prerequisites and have enough coins.',
  researchSuccessFormat: '{{name}} complete! {{mods}}.',
  attempt: 'Attempt',
  percentSuccess: '{{pct}}% success',
  claimRewardFormat: 'Claim {{reward}} ⬡',
  completeQuestToClaim: 'Complete the quest to claim the reward',
  questStreakKeep: 'Streak ×{{n}} · claim next within 5 min to keep it',
  streakExpired: 'Streak expired. Claim a quest to start a new streak.',
  achievementToast: 'Achievement: {{name}}',
  welcomeBack: 'Welcome back! +{{coins}} coins while you were away.',
  welcomeBackCapped: 'Welcome back! +{{coins}} coins while you were away (capped at 12h).',
  luckyToast: '★ LUCKY! +{{coins}} ⬡',
  questStreakToastFormat: 'Quest streak ×{{n}}! +{{pct}}% reward',
  milestoneToastFormat: 'Milestone: {{coins}} total coins earned!',
  dailyBonusToastFormat: 'Daily bonus: +{{n}} ⬡',
  criticalToastFormat: 'CRITICAL! +{{coins}} ⬡',
  prestigeMilestoneToastFormat: 'Prestige level {{level}}! +{{pct}}% production forever',
  crewStatFormat: 'Crew: {{n}} astronaut(s)',
  breakdownBase: 'Base',
  breakdownPlanets: 'planets',
  breakdownPrestige: 'prestige',
  breakdownCrew: 'crew',
  breakdownResearch: 'research',
  breakdownEvent: 'event',
  nextMilestoneFormat: '{{remaining}} ⬡ to unlock {{title}}',
  toUnlock: 'to unlock',
  nextEventInFormat: 'Next event in {{time}}',
  eventBadgeTitle: '{{name}}: ×{{mult}} production',
  collapseSection: 'Collapse',
  expandSection: 'Expand',
  statisticsTitle: 'Statistics',
  statisticsIntro: 'Track your mining empire: economy, progression, and activity. Chart data is saved across sessions.',
  chartsTitle: 'Charts',
  lastXMin: 'Last {{n}} min',
  lastXHours: 'Last {{n}} h',
  coinsOverTime: 'Coins over time',
  productionOverTime: 'Production over time',
  totalCoinsEverChart: 'Total coins ever',
  economyTitle: 'Economy',
  productionBreakdownTitle: 'Production breakdown',
  progressionTitle: 'Progression',
  activityTitle: 'Activity',
  questsEventsTitle: 'Quests & events',
  achievementsTitle: 'Achievements',
  currentCoins: 'Current coins',
  productionEffective: 'Production (effective)',
  totalCoinsEverLabel: 'Total coins ever',
  avgCoinsPerClick: 'Avg coins per click (session)',
  baseRate: 'Base rate',
  planetBonus: 'Planet bonus',
  prestigeBonus: 'Prestige bonus',
  crewBonus: 'Crew bonus',
  eventMultiplier: 'Event multiplier',
  researchBonus: 'Research bonus',
  planetsCount: 'Planets',
  upgradesOwned: 'Upgrades owned',
  slotsUsedTotal: 'Slots used / total',
  prestigeLevel: 'Prestige level',
  crewFree: 'Crew (free)',
  crewAssigned: 'Crew (assigned)',
  clicksLifetime: 'Clicks (lifetime)',
  clicksSession: 'Clicks (this session)',
  coinsFromClicksSession: 'Coins from clicks (session)',
  totalPlayTime: 'Total play time',
  sessionDuration: 'Session duration',
  questStreak: 'Quest streak',
  activeEvents: 'Active events',
  nextEventIn: 'Next event in',
  unlockedLabel: 'Unlocked',
  chartMinMax: 'Min {{min}} · Max {{max}}',
  chartAriaCoins: 'Coins over time line chart. Hover to see values.',
  chartAriaProduction: 'Production over time line chart. Hover to see values.',
  chartAriaTotalEver: 'Total coins ever line chart. Hover to see values.',
  upgradeGroupEarly: 'Early',
  upgradeGroupMid: 'Mid',
  upgradeGroupLate: 'Late',
  buyLabel: 'Buy',
  buyLabelPlusOne: '+1',
  maxLabel: 'Max',
  maxLabelCount: 'Max ({{n}})',
  recommended: 'Recommended',
  needAstronauts: 'Need {{n}} astronaut(s). Hire crew in the Crew section.',
  noFreeSlot: 'No free slot. Add a slot to a planet or buy a new planet!',
  needCoinsAndSlot: 'Need {{cost}} and a free slot.',
  buyUpgradeTitle: 'Buy {{name}} · {{cost}}',
  needCrewToBuy: 'Need more crew to buy this upgrade.',
  needCoinsForOne: 'Need {{cost}} to buy at least one.',
  noSlotsOrCoins: 'No free slots or not enough coins/crew to buy more.',
  toPlanet: 'To',
  assignToPlanet: 'Assign to planet',
  tierLabel: 'Tier {{n}}',
  crewBadgeTitle: 'Cost in astronauts (spent when you buy)',
  crewCostShort: '{{n}} crew',
  upgradeUsesSlot: '1 slot',
  upgradeNoSlot: 'No slot',
  upgradePlanetAffinityTitle: 'Production by planet type',
  slots: 'slots',
  addSlotBtn: '+1 slot · {{cost}} ⬡',
  addSlotTooltip: 'Add one upgrade slot · {{cost}} ⬡',
  needCoinsForSlot: 'Need {{cost}} ⬡ to add a slot',
  sendExpeditionBtn: 'Send expedition ({{cost}} ⬡ + {{n}} crew)',
  sendExpeditionTooltip: 'Send {{n}} astronauts on expedition. Risk: some may die (25% each). If all die, planet not discovered. Cost: {{cost}} ⬡',
  needForExpedition: 'Need {{cost}} ⬡ and {{n}} astronauts to launch expedition',
  planetCardTitle: '{{used}}/{{max}} slots',
  planetCardTitleProd: '{{used}}/{{max}} slots · +{{pct}}% prod from planets',
  planetInfoType: 'Type',
  planetInfoSlots: 'Slots',
  planetInfoProduction: 'Production',
  planetInfoHousing: 'Housing',
  planetInfoHousingLine: '{{n}} module(s) · +{{crew}} crew capacity',
  planetInfoEquipment: 'Equipment',
  planetInfoTitle: 'Planet info',
  hireAstronautCost: 'Hire astronaut · {{cost}} ⬡',
  noCrewYetMax: 'No crew yet (max {{max}})',
  crewLineAssigned: '{{assigned}} on equipment · 0 free (hire more for +% or discover planets to raise cap)',
  crewLineFree: '{{free}} free · +{{pct}}% production | {{assigned}} on equipment ({{total}}/{{max}})',
  crewLineAstronauts: '{{free}}/{{max}} astronaut(s) · +{{pct}}% production',
  crewOperatesHint: 'Hire crew to buy tier 2+ upgrades (each costs coins + astronauts).',
  crewOperatesNext: '{{free}} available. Next: {{name}} costs {{n}} crew.',
  crewOperatesUpgrades: '{{n}} upgrade(s) operated by crew.',
  crewOperatesAvailable: '{{free}} available.',
  freeAstronautsTitle: 'Free astronauts: +2% production each. Max crew: {{max}} (based on {{planets}} planet(s)).',
  prestigeConfirmDescLevel: "You'll reset to 0 coins and 1 planet. You keep Prestige level {{level}} (+{{pct}}% production forever).",
  prestigeRewardsTitle: 'Prestige rewards',
  prestigeRewardsIntro: 'What you gain at each prestige level:',
  prestigeReward1: 'Prestige 1: +5% production forever. Unlocks all click bonuses: Lucky / Super Lucky / Critical clicks, Combo multiplier, and Research +% click (skill tree). Before prestige 1, each click gives only 1 coin.',
  prestigeRewardLevelFormat: 'Prestige {{level}}: +{{prod}}% production. Unlocks: +{{click}}% click forever.',
  prestigeRewardsWhatFor: 'What do I get?',
  eachPerSecond: '+{{n}} /s each',
  totalPerSecond: 'Total: +{{n}}/s',
  needCoinsToBuy: 'Need {{cost}}{{crew}} to buy.',
  needCoinsAndCrew: 'Need {{cost}} + {{crew}} and a free slot.',
  maxBuyTooltip: 'Buy as many as you can afford with current slots',
  locked: 'Locked',
  debugCoinsRaw: 'Coins (raw)',
  debugProductionBase: 'Production (base)',
  debugProductionEffective: 'Production (effective)',
  debugEventMult: 'Event mult',
  debugPrestigeLevel: 'Prestige level',
  debugPlanets: 'Planets',
  debugUpgradesTotal: 'Upgrades total',
  debugNextEventIn: 'Next event in',
  debugActiveEvents: 'Active events',
  progressionWelcomeTitle: 'Welcome to Stellar Miner',
  progressionWelcomeBody: 'Click the asteroid (or press Space) to mine coins. Your goal: grow your mining operation by buying upgrades, hiring crew, and expanding to new planets. Start by mining until you can afford your first upgrade!',
  progressionUpgradesTitle: 'Upgrades',
  progressionUpgradesBody: 'Spend coins to buy equipment that produces coins automatically. Each upgrade adds production per second. You can buy the same upgrade multiple times—each goes on a planet slot. Start with a Mining Robot (100 ⬡).',
  progressionCrewTitle: 'Crew',
  progressionCrewBody: 'Hire astronauts to boost your production (+2% per astronaut). Better upgrades require crew to operate—you spend astronauts when you buy those upgrades. Hire your first astronaut when you can afford it (75 ⬡).',
  progressionQuestTitle: 'Quests',
  progressionQuestBody: 'Complete quests for bonus coins and rewards. Each quest has a target (e.g. mine X coins, buy upgrades). Claim within 5 minutes of completion for a streak bonus. Check the Quest section above.',
  progressionPlanetsTitle: 'Planets',
  progressionPlanetsBody: 'Send astronauts on expeditions to discover new planets (+5% production each). Some may die during the mission; if all die, the planet is not discovered. You can also add slots to existing planets.',
  progressionEventsTitle: 'Random events',
  progressionEventsBody: 'Space is full of surprises. Random events will now occasionally boost or reduce your production for a short time. Watch the event badges and plan around them!',
  progressionResearchTitle: 'Scientific Research',
  progressionResearchBody: 'Skill tree: attempt to unlock nodes for +% production and +% click. Each attempt can succeed or fail (coins lost on failure). Resets on Prestige.',
  progressionPrestigeTitle: 'Prestige',
  progressionPrestigeBody: 'When you reach 1,000,000 coins you can Prestige: reset coins and planets to gain +5% production per prestige level forever. Use it to progress faster on each new run.',
  versionLabel: 'Version',
  changelog: 'Changelog',
  whatsNew: "What's new",
  updateAvailable: 'New update',
  newUpdateAvailable: 'A new version is available. Open settings to see what\'s new.',
  infoTitle: "What's new",
  infoVersionLabel: 'Version',
} as const;

const stringsFr: Record<keyof typeof stringsEn, string> = {
  appTitle: 'STELLAR MINER',
  appSubtitle: 'Minez des pièces. Achetez des améliorations. Conquérez la ceinture.',
  settings: 'Paramètres',
  openSettings: 'Ouvrir les paramètres',
  close: 'Fermer',
  language: 'Langue',
  languageEn: 'English',
  languageFr: 'Français',
  starfieldSpeed: 'Vitesse du champ d’étoiles',
  showOrbitLines: 'Afficher les orbites',
  clickParticles: 'Particules au clic',
  compactNumbers: 'Nombres compacts (1,2K)',
  spaceKeyRepeat: 'Répétition de la touche Espace (maintenir pour miner)',
  layout: 'Disposition',
  layoutTabs: 'Onglets',
  layoutOnePage: 'Une page',
  pauseWhenBackground: 'Pause de la production quand l’onglet est en arrière-plan',
  exportSave: 'Exporter la sauvegarde',
  importSave: 'Importer la sauvegarde',
  exportSaveTitle: 'Copier la sauvegarde et télécharger en fichier',
  importSaveTitle: 'Charger une sauvegarde (remplace la partie en cours).',
  achievements: 'Succès',
  resetProgress: 'Réinitialiser la progression',
  resetConfirmTitle: 'Réinitialiser la progression ?',
  resetConfirmDesc: 'Pièces, planètes, améliorations, équipage et toute la progression seront perdus. Irréversible.',
  cancel: 'Annuler',
  resetAll: 'Tout réinitialiser',
  prestigeConfirmTitle: 'Prestige ?',
  prestigeConfirmDesc: 'Vous repartez à 0 pièce et 1 planète. Vous gardez le niveau Prestige et +5 % de production par niveau.',
  prestige: 'Prestige',
  gotIt: 'Compris',
  coins: 'Pièces',
  coinsTitle: 'Vos pièces. Dépensez-les en améliorations, équipage et planètes.',
  production: 'Production',
  productionTitle: 'Base × planètes × prestige × événements',
  gameSections: 'Sections du jeu',
  tabMine: 'Mine',
  tabBase: 'Base',
  tabResearch: 'Recherche',
  tabUpgrades: 'Améliorations',
  tabStats: 'Stats',
  mineZoneTitle: 'Cliquez ou Espace pour miner',
  quest: 'Quête',
  claim: 'Récupérer',
  prestigeHint: 'Réinitialisez pièces et planètes pour +5 % de production par niveau de prestige.',
  crew: 'Équipage',
  crewHint: 'Engagez des astronautes pour +2 % de production chacun. Les améliorations coûtent des pièces et des astronautes. Réinitialisé au Prestige.',
  noCrewYet: 'Pas encore d’équipage',
  hireAstronaut: 'Engager un astronaute',
  planets: 'Planètes',
  planetsHint: 'Chaque planète a des emplacements d’amélioration (extensibles). Plus de planètes = +5 % de production chacune. Envoyez des astronautes en expédition pour en découvrir une (certains peuvent mourir) ; si tous survivent ou au moins un revient, vous la découvrez. Ajoutez des emplacements pour étendre.',
  housing: 'Maison',
  housingHint: "Construisez une maison sur une planète pour augmenter la capacité d'équipage (+2 astronautes par module). Chaque module utilise 1 emplacement sur la planète.",
  housingNoSlot: 'Aucun emplacement libre sur les planètes. Ajoutez un emplacement ou utilisez-les pour des améliorations.',
  housingBuilt: 'construit(s)',
  housingBuildTooltip: "Construire une maison sur {{planet}} : {{cost}} ⬡ · 1 emplacement · +{{capacity}} capacité d'équipage.",
  needCoinsForHousing: 'Il faut {{cost}} ⬡ pour construire une maison.',
  buildHousingBtn: 'Construire une maison ({{cost}} ⬡)',
  buyNewPlanet: 'Envoyer une expédition',
  upgrades: 'Améliorations',
  upgradesHint: 'Chaque planète a un nombre limité d’emplacements (6 sur la première). Vous pouvez acheter chaque amélioration plusieurs fois ; chaque exemplaire utilise un emplacement. Ajoutez des emplacements ou découvrez des planètes pour en placer plus.',
  research: 'Recherche scientifique',
  researchHint: 'Arbre de compétences : tentez de débloquer des nœuds (+ % production et clic). Chaque tentative a un taux de succès ; échec = perte des pièces. Réinitialisé au Prestige.',
  invalidSaveFile: 'Fichier de sauvegarde invalide.',
  offlineIndicator: 'Vous êtes hors ligne. La progression peut ne pas être enregistrée.',
  reducedMotion: 'Réduire les animations',
  theme: 'Thème',
  themeLight: 'Clair',
  themeDark: 'Sombre',
  soundEnabled: 'Effets sonores',
  debug: 'Debug',
  closeDebug: 'Fermer le debug',

  starfieldSpeedSlow: 'Lent',
  starfieldSpeedNormal: 'Normal',
  starfieldSpeedFast: 'Rapide',
  debugTriggerEvent: 'Déclencher un événement',
  debugClearEvents: 'Effacer les événements',
  debugF3Hint: 'F3 pour afficher/masquer',
  firstPrestigeToast: 'Premier prestige !',
  firstUpgradeToast: 'Première amélioration !',
  firstNewPlanetToast: 'Première nouvelle planète !',
  firstAstronautToast: 'Premier astronaute !',
  expeditionDiscoveredWithDeaths: 'Découverte : {{name}} ! {{survivors}} astronaute(s) de retour. {{deaths}} perdu(s).',
  expeditionDiscoveredAllReturned: 'Découverte : {{name}} ! Tous les {{survivors}} astronaute(s) sont revenus.',
  expeditionFailed: 'Expédition échouée. Les {{n}} astronaute(s) ont péri. Planète non découverte.',
  chartLegendCoins: 'Pièces ⬡',
  chartLegendProduction: 'Production /s',
  chartLegendTotalEver: 'Total cumulé ⬡',
  chartLegendMinMaxPlaceholder: 'Min — · Max —',
  achievementLockedTitle: '???',
  researchFailedTryAgain: 'Échec de la recherche. Réessayez.',
  researching: 'Recherche en cours…',
  unknownResearch: 'Recherche inconnue.',
  prerequisitesNotMet: 'Prérequis non remplis ou déjà débloqué.',
  notEnoughCoins: 'Pas assez de pièces.',
  researchFailedCoinsSpent: 'Échec. Les pièces sont perdues. Réessayez.',
  researchRequires: 'Requis : {{names}}',
  researchSlotFree: '{{n}} amélioration(s) n’utilisent plus d’emplacement',
  researchCrewFree: '{{n}} amélioration(s) ne nécessitent plus d’équipage',
  researchUpgradeNoSlot: '{{name}} : n’utilise plus d’emplacement',
  researchUpgradeNoCrew: '{{name}} : ne nécessite plus d’équipage',
  researchUpgradeLessSlot: '{{name}} : utilise {{n}} emplacement(s) de moins',
  researchUpgradeLessCrew: '{{name}} : nécessite {{n}} équipage en moins',
  researchUnlockPath: 'Parcours : {{path}}',
  researchUnlockPathSingle: 'Parcours : {{name}}',
  researchEffectsLabel: 'Effets :',
  researchInfoTitle: 'Détails de la recherche',
  researchAttemptTooltip: 'Tenter ({{pct}} % de succès). En cas d’échec, les pièces sont perdues.',
  researchAttemptDisabled: 'Remplissez les prérequis et ayez assez de pièces.',
  researchSuccessFormat: '{{name}} terminé ! {{mods}}.',
  attempt: 'Tenter',
  percentSuccess: '{{pct}} % de succès',
  claimRewardFormat: 'Récupérer {{reward}} ⬡',
  completeQuestToClaim: 'Terminez la quête pour récupérer la récompense.',
  questStreakKeep: 'Série ×{{n}} · réclamez la prochaine sous 5 min pour la garder.',
  streakExpired: 'Série expirée. Réclamez une quête pour en commencer une nouvelle.',
  achievementToast: 'Succès : {{name}}',
  welcomeBack: 'Bon retour ! +{{coins}} pièces pendant votre absence.',
  welcomeBackCapped: 'Bon retour ! +{{coins}} pièces pendant votre absence (plafonné 12 h).',
  luckyToast: '★ CHANCE ! +{{coins}} ⬡',
  questStreakToastFormat: 'Série de quêtes ×{{n}} ! +{{pct}} % de récompense',
  milestoneToastFormat: 'Jalon : {{coins}} pièces gagnées au total !',
  dailyBonusToastFormat: 'Bonus quotidien : +{{n}} ⬡',
  criticalToastFormat: 'CRITIQUE ! +{{coins}} ⬡',
  prestigeMilestoneToastFormat: 'Niveau prestige {{level}} ! +{{pct}} % de production pour toujours',
  crewStatFormat: 'Équipage : {{n}} astronaute(s)',
  breakdownBase: 'Base',
  breakdownPlanets: 'planètes',
  breakdownPrestige: 'prestige',
  breakdownCrew: 'équipage',
  breakdownResearch: 'recherche',
  breakdownEvent: 'événement',
  nextMilestoneFormat: '{{remaining}} ⬡ pour débloquer {{title}}',
  toUnlock: 'pour débloquer',
  nextEventInFormat: 'Prochain événement dans {{time}}',
  eventBadgeTitle: '{{name}} : ×{{mult}} production',
  collapseSection: 'Replier',
  expandSection: 'Déplier',
  statisticsTitle: 'Statistiques',
  statisticsIntro: 'Suivez votre empire minier : économie, progression et activité. Les graphiques sont conservés entre les sessions.',
  chartsTitle: 'Graphiques',
  lastXMin: 'Dernières {{n}} min',
  lastXHours: 'Dernières {{n}} h',
  coinsOverTime: 'Pièces dans le temps',
  productionOverTime: 'Production dans le temps',
  totalCoinsEverChart: 'Total des pièces',
  economyTitle: 'Économie',
  productionBreakdownTitle: 'Détail de la production',
  progressionTitle: 'Progression',
  activityTitle: 'Activité',
  questsEventsTitle: 'Quêtes et événements',
  achievementsTitle: 'Succès',
  currentCoins: 'Pièces actuelles',
  productionEffective: 'Production (effective)',
  totalCoinsEverLabel: 'Total des pièces',
  avgCoinsPerClick: 'Moy. pièces par clic (session)',
  baseRate: 'Taux de base',
  planetBonus: 'Bonus planètes',
  prestigeBonus: 'Bonus prestige',
  crewBonus: 'Bonus équipage',
  eventMultiplier: 'Multiplicateur événement',
  researchBonus: 'Bonus recherche',
  planetsCount: 'Planètes',
  upgradesOwned: 'Améliorations possédées',
  slotsUsedTotal: 'Emplacements utilisés / total',
  prestigeLevel: 'Niveau prestige',
  crewFree: 'Équipage (libre)',
  crewAssigned: 'Équipage (assigné)',
  clicksLifetime: 'Clics (total)',
  clicksSession: 'Clics (cette session)',
  coinsFromClicksSession: 'Pièces des clics (session)',
  totalPlayTime: 'Temps de jeu total',
  sessionDuration: 'Durée de la session',
  questStreak: 'Série de quêtes',
  activeEvents: 'Événements actifs',
  nextEventIn: 'Prochain événement dans',
  unlockedLabel: 'Débloqués',
  chartMinMax: 'Min {{min}} · Max {{max}}',
  chartAriaCoins: 'Graphique des pièces dans le temps. Survolez pour voir les valeurs.',
  chartAriaProduction: 'Graphique de la production dans le temps. Survolez pour voir les valeurs.',
  chartAriaTotalEver: 'Graphique du total des pièces. Survolez pour voir les valeurs.',
  upgradeGroupEarly: 'Début',
  upgradeGroupMid: 'Milieu',
  upgradeGroupLate: 'Fin',
  buyLabel: 'Acheter',
  buyLabelPlusOne: '+1',
  maxLabel: 'Max',
  maxLabelCount: 'Max ({{n}})',
  recommended: 'Recommandé',
  needAstronauts: 'Il faut {{n}} astronaute(s). Engagez-en dans la section Équipage.',
  noFreeSlot: 'Aucun emplacement libre. Ajoutez un emplacement ou achetez une planète !',
  needCoinsAndSlot: 'Il faut {{cost}} et un emplacement libre.',
  buyUpgradeTitle: 'Acheter {{name}} · {{cost}}',
  needCrewToBuy: 'Il faut plus d’équipage pour acheter cette amélioration.',
  needCoinsForOne: 'Il faut {{cost}} pour en acheter au moins un.',
  noSlotsOrCoins: 'Pas d’emplacement libre ou pas assez de pièces/équipage.',
  toPlanet: 'Vers',
  assignToPlanet: 'Assigner à la planète',
  tierLabel: 'Niveau {{n}}',
  crewBadgeTitle: 'Coût en astronautes (dépensés à l’achat)',
  crewCostShort: '{{n}} équipage',
  upgradeUsesSlot: '1 emplacement',
  upgradeNoSlot: 'Aucun emplacement',
  upgradePlanetAffinityTitle: 'Production selon le type de planète',
  slots: 'emplacements',
  addSlotBtn: '+1 emplacement · {{cost}} ⬡',
  addSlotTooltip: 'Ajouter un emplacement d’amélioration · {{cost}} ⬡',
  needCoinsForSlot: 'Il faut {{cost}} ⬡ pour ajouter un emplacement',
  sendExpeditionBtn: 'Envoyer une expédition ({{cost}} ⬡ + {{n}} équipage)',
  sendExpeditionTooltip: 'Envoyez {{n}} astronautes en expédition. Risque : certains peuvent mourir (25 % chacun). Si tous meurent, la planète n’est pas découverte. Coût : {{cost}} ⬡',
  needForExpedition: 'Il faut {{cost}} ⬡ et {{n}} astronautes pour lancer l’expédition',
  planetCardTitle: '{{used}}/{{max}} emplacements',
  planetCardTitleProd: '{{used}}/{{max}} emplacements · +{{pct}} % prod. planètes',
  planetInfoType: 'Type',
  planetInfoSlots: 'Emplacements',
  planetInfoProduction: 'Production',
  planetInfoHousing: 'Habitat',
  planetInfoHousingLine: '{{n}} module(s) · +{{crew}} capacité équipage',
  planetInfoEquipment: 'Équipement',
  planetInfoTitle: 'Infos planète',
  hireAstronautCost: 'Engager un astronaute · {{cost}} ⬡',
  noCrewYetMax: 'Pas encore d’équipage (max {{max}})',
  crewLineAssigned: '{{assigned}} sur l’équipement · 0 libre',
  crewLineFree: '{{free}} libre · +{{pct}} % production | {{assigned}} sur l’équipement ({{total}}/{{max}})',
  crewLineAstronauts: '{{free}}/{{max}} astronaute(s) · +{{pct}} % production',
  crewOperatesHint: 'Engagez de l’équipage pour acheter les améliorations niveau 2+ (pièces + astronautes).',
  crewOperatesNext: '{{free}} disponible(s). Prochaine : {{name}} coûte {{n}} équipage.',
  crewOperatesUpgrades: '{{n}} amélioration(s) opérée(s) par l’équipage.',
  crewOperatesAvailable: '{{free}} disponible(s).',
  freeAstronautsTitle: 'Astronautes libres : +2 % production chacun. Max : {{max}} (selon {{planets}} planète(s)).',
  prestigeConfirmDescLevel: 'Vous repartez à 0 pièce et 1 planète. Vous gardez le niveau Prestige {{level}} (+{{pct}} % production pour toujours).',
  prestigeRewardsTitle: 'Récompenses de prestige',
  prestigeRewardsIntro: 'Ce que vous gagnez à chaque niveau de prestige :',
  prestigeReward1: 'Prestige 1 : +5 % production pour toujours. Débloque tous les bonus de clic : Lucky / Super Lucky / Critical, multiplicateur Combo, et + % clic recherche (arbre). Avant le prestige 1, chaque clic ne donne qu’1 pièce.',
  prestigeRewardLevelFormat: 'Prestige {{level}} : +{{prod}} % production. Débloque : +{{click}} % clic pour toujours.',
  prestigeRewardsWhatFor: 'Qu’est-ce que je gagne ?',
  eachPerSecond: '+{{n}}/s chacun',
  totalPerSecond: 'Total : +{{n}}/s',
  needCoinsToBuy: 'Il faut {{cost}}{{crew}} pour acheter.',
  needCoinsAndCrew: 'Il faut {{cost}} + {{crew}} et un emplacement libre.',
  maxBuyTooltip: 'Acheter autant que possible avec les emplacements actuels',
  locked: 'Verrouillé',
  debugCoinsRaw: 'Pièces (brut)',
  debugProductionBase: 'Production (base)',
  debugProductionEffective: 'Production (effective)',
  debugEventMult: 'Mult. événement',
  debugPrestigeLevel: 'Niveau prestige',
  debugPlanets: 'Planètes',
  debugUpgradesTotal: 'Total améliorations',
  debugNextEventIn: 'Prochain événement dans',
  debugActiveEvents: 'Événements actifs',
  progressionWelcomeTitle: 'Bienvenue dans Stellar Miner',
  progressionWelcomeBody: 'Cliquez sur l’astéroïde (ou Espace) pour miner des pièces. Objectif : développer votre opération en achetant des améliorations, en engageant de l’équipage et en découvrant des planètes. Minez jusqu’à pouvoir vous offrir votre première amélioration !',
  progressionUpgradesTitle: 'Améliorations',
  progressionUpgradesBody: 'Dépensez des pièces pour acheter de l’équipement qui produit des pièces automatiquement. Chaque planète a un nombre limité d’emplacements (6 sur la première) : chaque robot ou foreuse en utilise un. Commencez par un Robot minier (25 ⬡), puis passez aux milliers, millions et au-delà.',
  progressionCrewTitle: 'Équipage',
  progressionCrewBody: 'Engagez des astronautes pour booster la production (+2 % par astronaute). Les meilleures améliorations nécessitent de l’équipage ; vous dépensez des astronautes à l’achat. Engagez votre premier astronaute quand vous pouvez (75 ⬡).',
  progressionQuestTitle: 'Quêtes',
  progressionQuestBody: 'Terminez des quêtes pour des pièces et récompenses bonus. Chaque quête a un objectif (ex. miner X pièces, acheter des améliorations). Réclamez sous 5 minutes pour un bonus de série.',
  progressionPlanetsTitle: 'Planètes',
  progressionPlanetsBody: 'Envoyez des astronautes en expédition pour découvrir de nouvelles planètes (+5 % production chacune). Certains peuvent mourir ; si tous meurent, la planète n’est pas découverte. Vous pouvez aussi ajouter des emplacements aux planètes existantes.',
  progressionEventsTitle: 'Événements aléatoires',
  progressionEventsBody: "L'espace réserve des surprises. Des événements aléatoires vont désormais parfois augmenter ou réduire ta production pendant un court moment. Surveille les badges d'événements !",
  progressionResearchTitle: 'Recherche scientifique',
  progressionResearchBody: 'Arbre de compétences : tentez de débloquer des nœuds pour + % production et + % clic. Chaque tentative peut réussir ou échouer (pièces perdues en cas d’échec). Réinitialisé au Prestige.',
  progressionPrestigeTitle: 'Prestige',
  progressionPrestigeBody: 'À 1 000 000 pièces vous pouvez Prestige : réinitialiser pièces et planètes pour +5 % de production par niveau de prestige pour toujours. Pour progresser plus vite à chaque run.',
  versionLabel: 'Version',
  changelog: 'Journal des modifications',
  whatsNew: 'Nouveautés',
  updateAvailable: 'Nouvelle mise à jour',
  newUpdateAvailable: 'Une nouvelle version est disponible. Ouvrez les paramètres pour voir les nouveautés.',
  infoTitle: 'Nouveautés',
  infoVersionLabel: 'Version',
};

export type StringKey = keyof typeof stringsEn;

const translations: Record<'en' | 'fr', Record<StringKey, string>> = {
  en: stringsEn,
  fr: stringsFr,
};

export function t(key: StringKey): string {
  const lang = getSettings().language ?? 'en';
  const bundle = translations[lang] ?? translations.en;
  return bundle[key] ?? stringsEn[key] ?? key;
}

/** Replace {{key}} placeholders in the translation for key. */
export function tParam(key: StringKey, params: Record<string, string | number>): string {
  let s = t(key);
  for (const [k, v] of Object.entries(params)) {
    s = s.replace(new RegExp(`\\{\\{${k}\\}\\}`, 'g'), String(v));
  }
  return s;
}

/** For backward compatibility: same keys as stringsEn. */
export const strings = stringsEn as Record<string, string>;

/** Update all elements with data-i18n attribute. Call on mount and when language changes. */
export function applyTranslations(): void {
  if (typeof document === 'undefined') return;
  document.querySelectorAll<HTMLElement>('[data-i18n]').forEach((el) => {
    const key = el.getAttribute('data-i18n');
    if (key && key in stringsEn) el.textContent = t(key as StringKey);
  });
  document.querySelectorAll<HTMLElement>('[data-i18n-title]').forEach((el) => {
    const key = el.getAttribute('data-i18n-title');
    if (key && key in stringsEn) el.title = t(key as StringKey);
  });
  document.querySelectorAll<HTMLElement>('[data-i18n-aria-label]').forEach((el) => {
    const key = el.getAttribute('data-i18n-aria-label');
    if (key && key in stringsEn) el.setAttribute('aria-label', t(key as StringKey));
  });
}
